<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 11: dplyr Subsetting – Introduction to R Programming: Goal, Code, Verify, Reflect</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/06-curiosity/curiosity.html" rel="next">
<link href="../../chapters/05-openmindedness/ch10-and-or-in.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-30a6f3117ec04dc5da00a6077361ea08.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4a48981ed7de43aebb597d4e7fd5f8e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/05-openmindedness/openmindedness.html">Openmindedness</a></li><li class="breadcrumb-item"><a href="../../chapters/05-openmindedness/ch11-dplyr-subsetting.html"><span class="chapter-title">Chapter 11: dplyr Subsetting</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Introduction to R Programming: Goal, Code, Verify, Reflect</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lorrainegaudio/guided-activities-for-learning-R-workflow" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../front-matter/preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/01-tenacity/tenacity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tenacity</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-tenacity/ch01-navigation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 1: Navigation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-tenacity/ch02-scripts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 2: Scripts</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/02-transparency/transparency.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transparency</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-transparency/ch03-vectors.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 3: Vector</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-transparency/ch04-structures.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 4:️ Structuers</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/03-courage/courage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Courage</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-courage/ch05-help.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 5 Help!</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-courage/ch05-help-prompting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 5 Help! Prompting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-courage/ch06-missing-values.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 6: Missing Values</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/04-autonomy/autonomy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Autonomy</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/04-autonomy/ch07-importing-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 7: Importing Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/04-autonomy/ch08-indexing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 8: Indexing</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/05-openmindedness/openmindedness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Openmindedness</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/05-openmindedness/ch09-github.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 9: Git and GitHub</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/05-openmindedness/ch10-and-or-in.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 10: And, Or, and Membership</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/05-openmindedness/ch11-dplyr-subsetting.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Chapter 11: dplyr Subsetting</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/06-curiosity/curiosity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Curiosity</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/06-curiosity/ch12-recoding.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 12: Recoding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/06-curiosity/ch13-grouped-summaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 13: Grouped Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/06-curiosity/ch14-chaining.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 14: Chaining</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/07-thoroughness/thoroughness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thoroughness</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/07-thoroughness/ch15-probability-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 15: Probability functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/07-thoroughness/ch16-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 16: ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/07-thoroughness/ch17-string-detect.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 17: String Detect</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#quarto" id="toc-quarto" class="nav-link" data-scroll-target="#quarto">Quarto</a>
  <ul class="collapse">
  <li><a href="#notebook-quarto" id="toc-notebook-quarto" class="nav-link" data-scroll-target="#notebook-quarto">R Notebook → Quarto</a></li>
  <li><a href="#yaml-header" id="toc-yaml-header" class="nav-link" data-scroll-target="#yaml-header">The YAML Header</a></li>
  <li><a href="#markdown-headings" id="toc-markdown-headings" class="nav-link" data-scroll-target="#markdown-headings">Markdown Headings</a></li>
  <li><a href="#memoing" id="toc-memoing" class="nav-link" data-scroll-target="#memoing">Memoing in Quarto</a></li>
  </ul></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">📦 Packages</a></li>
  <li><a href="#the-pipe" id="toc-the-pipe" class="nav-link" data-scroll-target="#the-pipe">The Pipe (<code>%&gt;%</code>)</a></li>
  <li><a href="#selecting-columns" id="toc-selecting-columns" class="nav-link" data-scroll-target="#selecting-columns">Selecting Columns</a>
  <ul class="collapse">
  <li><a href="#positive-selection" id="toc-positive-selection" class="nav-link" data-scroll-target="#positive-selection">Positive Selection</a></li>
  <li><a href="#negative-selection" id="toc-negative-selection" class="nav-link" data-scroll-target="#negative-selection">Negative Selection</a></li>
  <li><a href="#piping-with-select" id="toc-piping-with-select" class="nav-link" data-scroll-target="#piping-with-select">Piping with Select</a></li>
  <li><a href="#subset-with-select" id="toc-subset-with-select" class="nav-link" data-scroll-target="#subset-with-select">Subset with Select</a></li>
  </ul></li>
  <li><a href="#filtering-rows" id="toc-filtering-rows" class="nav-link" data-scroll-target="#filtering-rows">Filtering Rows</a>
  <ul class="collapse">
  <li><a href="#single-condition" id="toc-single-condition" class="nav-link" data-scroll-target="#single-condition">Single Condition</a></li>
  <li><a href="#piping-with-filter" id="toc-piping-with-filter" class="nav-link" data-scroll-target="#piping-with-filter">Piping with Filter</a></li>
  <li><a href="#multiple-conditions-and" id="toc-multiple-conditions-and" class="nav-link" data-scroll-target="#multiple-conditions-and">Multiple Conditions with AND</a></li>
  <li><a href="#multiple-conditions-or" id="toc-multiple-conditions-or" class="nav-link" data-scroll-target="#multiple-conditions-or">Multiple Conditions with OR</a></li>
  </ul></li>
  <li><a href="#filter-and-select" id="toc-filter-and-select" class="nav-link" data-scroll-target="#filter-and-select">filter() AND select()</a></li>
  <li><a href="#one-application" id="toc-one-application" class="nav-link" data-scroll-target="#one-application">One Application</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#chapter-terms" id="toc-chapter-terms" class="nav-link" data-scroll-target="#chapter-terms">Chapter Terms</a></li>
  <li><a href="#practice-space" id="toc-practice-space" class="nav-link" data-scroll-target="#practice-space">📝 Practice Space</a>
  <ul class="collapse">
  <li><a href="#task-0" id="toc-task-0" class="nav-link" data-scroll-target="#task-0">Task 0</a></li>
  <li><a href="#task-1" id="toc-task-1" class="nav-link" data-scroll-target="#task-1">Task 1</a></li>
  <li><a href="#task-2" id="toc-task-2" class="nav-link" data-scroll-target="#task-2">Task 2</a></li>
  <li><a href="#task-3" id="toc-task-3" class="nav-link" data-scroll-target="#task-3">Task 3</a></li>
  <li><a href="#task-4" id="toc-task-4" class="nav-link" data-scroll-target="#task-4">Task 4</a></li>
  <li><a href="#task-5" id="toc-task-5" class="nav-link" data-scroll-target="#task-5">Task 5</a></li>
  <li><a href="#task-6" id="toc-task-6" class="nav-link" data-scroll-target="#task-6">Task 6</a></li>
  <li><a href="#task-7" id="toc-task-7" class="nav-link" data-scroll-target="#task-7">Task 7</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/05-openmindedness/openmindedness.html">Openmindedness</a></li><li class="breadcrumb-item"><a href="../../chapters/05-openmindedness/ch11-dplyr-subsetting.html"><span class="chapter-title">Chapter 11: dplyr Subsetting</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Chapter 11: dplyr Subsetting</span></h1>
<p class="subtitle lead">Selecting columns and filtering rows with the pipe</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>In this chapter, you will learn how to subset data efficiently with <code>dplyr</code> by combining the pipe <code>%&gt;%</code> with two core verbs: <code>select()</code> for choosing columns and <code>filter()</code> for keeping rows that meet specific conditions. You will also continue working in Quarto, which is the course’s reproducible workflow for combining code, results, and written interpretation in one document. Together, these tools help you move from writing individual R commands to building a clear, repeatable analysis process. The chapter closes with applied practice using datasets such as 🚗 <code>mtcars</code>, 🌐 <code>gapminder</code>, 🔫 <code>murders</code>, and ☣️ <code>us_contagious_diseases</code>.</p>
<p>This chapter matters because subsetting is one of the most common tasks in data analysis. Before you can graph, summarize, model, or answer a research question, you usually need to isolate the relevant cases and variables. In later coursework, you will rely on these skills to prepare datasets for visualization, descriptive statistics, hypothesis testing, and project-based analysis. In professional data work, analysts constantly filter records, choose relevant fields, remove duplicates, and create smaller, targeted datasets for reporting and decision-making. Learning to do this with readable <code>dplyr</code> code will make your work faster, easier to check, and easier for other people to follow.</p>
<p>🤔 This chapter also asks you to practice open-mindedness as a coding habit. Base R brackets and <code>dplyr</code> verbs can often solve the same subsetting problem. Your job is not to decide that one method is always better. Your job is to compare the options, check the result, and choose the version that makes the logic clearest for the task.</p>
<p>By the end of Chapter 11 you will be able to:</p>
<ul>
<li><p>🔗 Use the pipe <code>%&gt;%</code> to connect multiple data-wrangling steps into a readable workflow.</p></li>
<li><p>🧱 Distinguish between <code>select()</code> for choosing columns and <code>filter()</code> for keeping rows.</p></li>
<li><p>🎯 Apply <code>select()</code> to keep, reorder, or exclude variables from a data frame.</p></li>
<li><p>🕵️ Apply <code>filter()</code> to keep rows that meet one or more logical conditions.</p></li>
<li><p>⚖️ Construct filtering conditions with relational operators such as <code>&gt;</code>, <code>&lt;</code>, <code>==</code>, <code>!=</code>, <code>&lt;=</code>, and <code>&gt;=</code>.</p></li>
<li><p>🧺 Combine conditions with <code>&amp;</code>, <code>|</code>, and <code>%in%</code> to create multi-criteria subsets.</p></li>
<li><p>🧠 Interpret how Boolean logic affects which observations are kept in a dataset.</p></li>
<li><p>🔄 Build pipelines that combine <code>filter()</code> and <code>select()</code> to create focused, analysis-ready data subsets.</p></li>
<li><p>📋 Produce smaller, relevant datasets that are ready for later visualization, summarization, and modeling.</p></li>
<li><p>📝 Use Quarto to organize code, output, and written interpretation in a reproducible analysis document.</p></li>
</ul>
<p>Keep these goals in mind as you move through each section.</p>
</section>
<section id="quarto" class="level2">
<h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
<p>In earlier chapters, you used an R Notebook as a reproducible thinking document: code, output, and memo-style writing in one place. <span class="glossary-term" data-term="Quarto">Quarto</span> keeps that same basic workflow, but the file is usually a <code>.qmd</code> file instead of an <code>.Rmd</code> file.</p>
<p>The biggest changes are:</p>
<ul>
<li>Quarto files use the <code>.qmd</code> file extension.</li>
<li>The YAML header uses <code>format:</code> instead of the older R Markdown <code>output:</code> style.</li>
<li>Code chunk options are written as YAML-style lines that begin with <code>#|</code> inside the code chunk.</li>
<li>You <span class="glossary-term" data-term="Render">render</span> a Quarto document with the render button instead of knitting an R Notebook.</li>
</ul>
<p>Quarto is useful because it gives you a clean way to combine code, output, and written explanation in one document. It also supports more flexible publishing formats and can work with multiple coding languages, including R, Python, Julia, and Observable JavaScript. In this course, we will use R with Quarto.</p>
<p>🤔 This is an open-minded tool shift. A Quarto document does much of what your R Notebook did, but the file type and setup details are a little bit different. Ask yourself: “What stays the same about my workflow, and what changes?”</p>
<p>To learn more about Quarto, check out the <a href="https://quarto.org/">Quarto website</a>. You can also find a helpful <a href="https://rstudio.github.io/cheatsheets/quarto.pdf">Quarto Cheat Sheet</a>.</p>
<section id="notebook-quarto" class="level3">
<h3 class="anchored" data-anchor-id="notebook-quarto">R Notebook → Quarto</h3>
<p>Quarto will be similar to an R Notebook in several ways. You still write normal paragraphs outside code chunks. You still run R code inside chunks. You still use Markdown headings to create an outline. You still render the document to create a readable HTML report.</p>
<p>What changes is the file extension, the YAML header, and the way chunk options are written.</p>
<p>🎯 Create a Quarto file.</p>
<ol type="1">
<li>For those of you who <strong>have GitHub</strong> and a course project, navigate to your course folder and open your course project. This will open RStudio. Click <strong>Pull</strong> in the Git pane to get the latest version of the course materials. After completing your work, save, stage, commit, and push.</li>
</ol>
<p>If you <strong>do not have GitHub</strong> or a course project, open RStudio and set your working directory to your course folder.</p>
<ol start="2" type="1">
<li>Open a new Quarto document in your course folder and save it as: <code>chapter11_notes.qmd</code> (<code>File &gt; New File &gt; Quarto Document</code>).</li>
</ol>
<p>Just like an R Notebook template, a new Quarto file will open with sample text. Start fresh:</p>
<ul>
<li>Keep the YAML header at the top.</li>
<li>Delete the example body text below it.</li>
<li>Replace that content with your own notes, code, and memos.</li>
</ul>
<p>✅ Check that your file ends in <code>.qmd</code>, not <code>.Rmd</code>.</p>
<p>🗣 The <code>.qmd</code> file is the editable Quarto document. The rendered <code>.html</code> file is the readable report created from it.</p>
<p>🤔 An <code>.Rmd</code> notebook and a <code>.qmd</code> document both support reproducible work, but they organize some settings differently. As you build out the Quarto notes, ask yourself: “Which file type feels easier for me to set up, read, and render?”</p>
</section>
<section id="yaml-header" class="level3">
<h3 class="anchored" data-anchor-id="yaml-header">The YAML Header</h3>
<p>At the top of the document is the <span class="glossary-term" data-term="YAML Header">YAML header</span>. This is document metadata. In Quarto, the header is still surrounded by three dashes (<code>---</code>) and uses <code>key: value</code> pairs. Quarto uses fields such as <code>title</code>, <code>subtitle</code>, <code>author</code>, <code>date</code>, <code>format</code>, and <code>execute</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span><span class="kw">:</span><span class="at"> </span><span class="st">"Chapter 11 Notes"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">subtitle</span><span class="kw">:</span><span class="at"> </span><span class="st">"dplyr Subsetting"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">author</span><span class="kw">:</span><span class="at"> </span><span class="st">"YOUR NAME"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">date</span><span class="kw">:</span><span class="at"> today</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">format</span><span class="kw">:</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">html</span><span class="kw">:</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">code-fold</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">execute</span><span class="kw">:</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">warning</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">message</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<section id="yaml-parts" class="level4">
<h4 class="anchored" data-anchor-id="yaml-parts">What each part does:</h4>
<ul>
<li><p><code>title:</code> gives your document a title.</p></li>
<li><p><code>subtitle:</code> gives your document a subtitle.</p></li>
<li><p><code>author:</code> puts your name on the document.</p></li>
<li><p><code>date: today</code> inserts the current local date automatically. <a href="https://quarto.org/docs/reference/dates.html">Quarto Dates and Date Formatting</a> has more options for date formatting and dynamic date keywords.</p></li>
<li><p><code>format:</code> tells Quarto what kind of output to create.</p></li>
<li><p><code>html:</code> tells Quarto to render the document as an HTML file.</p></li>
<li><p><code>code-fold: false</code> keeps code visible in the HTML report. If you change this to <code>true</code>, readers can collapse and expand the code.</p></li>
<li><p><code>execute:</code> sets default chunk behavior for the whole document.</p></li>
<li><p><code>warning: true</code> and <code>message: true</code> mean warnings and messages will appear in the rendered HTML if your code produces them. You can change these to <code>false</code> later when you want a cleaner final report, but for learning, seeing messages and warnings can help you understand what R is doing.</p></li>
</ul>
<p>🤔 Notice that YAML uses lowercase <code>true</code> and <code>false</code>. R uses uppercase <code>TRUE</code> and <code>FALSE</code>. Same idea, different file language. Ask yourself: “Am I writing YAML settings, or am I writing R code?”</p>
</section>
</section>
<section id="markdown-headings" class="level3">
<h3 class="anchored" data-anchor-id="markdown-headings">Markdown Headings</h3>
<p>Quarto uses Markdown for normal text, just like your notebook work. Headings are created with <code>#</code>, <code>##</code>, <code>###</code>, and so on. These headings create the structure of your document.</p>
<p>Use this outline in your notes file:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">## Quarto</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Packages</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Pipe</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Selecting Columns</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Filtering Rows</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## filter() and select()</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">## Application</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="memoing" class="level3">
<h3 class="anchored" data-anchor-id="memoing">Memoing in Quarto</h3>
<p>Quarto is not just for tracking your R code. It is also where you document your thinking, reasoning, and understanding. Your memos should usually be written as normal text outside code chunks, not jammed into code chunk comments.</p>
<p>Outside a code chunk, write normal sentences and paragraphs. This is where most of your memoing goes.</p>
<p>Inside a code chunk, write R code. If you want to leave yourself a short note about a specific line of code, use <code>#</code> so R treats it as a comment.</p>
<p>A Quarto R code chunk still uses fenced backticks with <code>{r}</code>. The difference is that chunk options are written as YAML-style lines beginning with <code>#|</code> at the top of the chunk.</p>
<p>The <code>#</code> symbol means different things depending on where you type it:</p>
<ul>
<li>Outside a code chunk, <code>#</code> creates a Markdown heading.</li>
<li>Inside a code chunk, <code>#</code> creates an R comment.</li>
<li>At the top of a Quarto code chunk, <code>#|</code> sets a chunk option.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># your R code</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 The <code>eval=FALSE</code> chunk option means the code will not run when you render the document. This is useful for example code, code that you are discussing but not running, or code that installs packages.</p>
<p>🤔 This is a readability choice. Quarto gives you easy to understand control over what code runs and what appears in the final report. Ask yourself: “Should this chunk run, or is it here only as an example?”</p>
<p><strong>💡 Test render.</strong></p>
<hr>
<p>You can also use <code>#| eval=FALSE</code> in code chunks that contain <code>install.packages()</code> instead of commenting out each line with <code>#</code>. Let’s see that in action next.</p>
</section>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">📦 Packages</h2>
<p>You will need the <code>dplyr</code> and <code>dslabs</code> packages installed and loaded to follow along with the code examples in this chapter.</p>
<p>The <code>dplyr</code> package is part of the <span class="glossary-term" data-term="Tidyverse">tidyverse</span>, a collection of R packages designed for data science. The <span class="glossary-term" data-term="dplyr">dplyr package</span> gives you data-wrangling functions called [verbs]{.glossary-term data-term=“Verbs”. These verbs help you work with data frames in readable steps. In this chapter, we will focus on <code>select()</code> for choosing columns and <code>filter()</code> for keeping rows.</p>
<p>🧠 Recall that you only need to install a package <strong>once</strong> on your computer. After a package is installed, you should not try to re-install it every time you render a document. In Quarto, one clean option is to put <code>#| eval=FALSE</code> at the top of the install chunk. That keeps the code visible in your document, but prevents Quarto from running it during render.</p>
<p>You should already have dslabs from previous chapters, but if not, install it now.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dslabs"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>✅ Check that the chunk option says <code>#| eval=FALSE</code>. This means the install code will be shown in your document but will not run when you render.</p>
<p>🗣 The <code>install.packages()</code> function downloads a package to your computer. You usually only need to do that once. The <code>#| eval=FALSE</code> option is useful here because reinstalling packages every time you render your report is unnecessary and can slow down or interrupt the render.</p>
<p>🤔 This is a Quarto file-choice moment. In an R Notebook, you may have commented out install code with <code>#</code>. In Quarto, you can use a chunk option instead. Ask yourself: “Do I want this code to appear in my report, run during render, or both?”</p>
<p>After installing the packages, you need to load them into your R session using the <code>library()</code> function. Each time you open R, you need to load the packages you plan to use. Loading a package makes its functions available for your current R session.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<p>✅ Check that both packages load without an error.</p>
<p>🗣 The <code>library()</code> function loads an installed package into the current R session. Unlike <code>install.packages()</code>, <code>library()</code> needs to run each time you start a new R session and want to use that package.</p>
<p>You may see messages when packages load. Messages are not always errors. Read them first before assuming something is broken.</p>
<p><strong>💡 Test render.</strong></p>
<p>🤔 If you want to hide package messages or warnings in a final report, you can use Quarto chunk options such as <code>#| message=FALSE</code> or <code>#| warning=FALSE</code>. For now, it is fine to leave messages visible while you are learning because they give you information about what R is doing.</p>
<hr>
<p>Now that we have <code>dplyr</code> and <code>dslabs</code> installed and loaded, we can use their functions to manipulate data frames. Let’s start with the pipe operator.</p>
</section>
<section id="the-pipe" class="level2">
<h2 class="anchored" data-anchor-id="the-pipe">The Pipe (<code>%&gt;%</code>)</h2>
<p>The <code>dplyr</code> package helps you manipulate data frames. You can use it to filter rows, select columns, create variables, summarize data, and arrange rows.</p>
<p>One reason people like <code>dplyr</code> is that it makes code easier to read using the <span class="glossary-term" data-term="Pipe">pipe</span>: <code>%&gt;%</code>. The pipe lets you chain steps together in a readable order from left to right. You can read the pipe as <strong>“and then”</strong> or <strong>“goes into.”</strong></p>
<p>The pipe takes the object on the left and sends it into the function on the right.</p>
<p>In tidyverse code, the pipe in action looks like this:</p>
<p><code>x %&gt;% f()</code></p>
<p>This means:</p>
<p>Start with <code>x</code>, and then apply <code>f()</code>.</p>
<p>You may also see the base R pipe, <code>|&gt;</code>, in newer R code. In this chapter, we will use the tidyverse pipe, <code>%&gt;%</code>, because it is common in <code>dplyr</code> examples.</p>
<p>🎯 See how the pipe works with a simple <code>head()</code> example using the 🚗 <code>mtcars</code> dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
</div>
<p>✅ Check that the output shows the first six rows of <code>mtcars</code>.</p>
<p>🗣 This is equivalent to <code>head(mtcars)</code>, but the pipe version reads more like a sequence of actions: start with <code>mtcars</code>, and then show the first few rows.</p>
<p>🤔 <code>head(mtcars)</code> and <code>mtcars %&gt;% head()</code> give the same result. The question is not “Which one is always better?” The question is: “Which version makes the workflow easier to read for this task?”</p>
<p>It is common to break lines after the pipe for readability, especially when chaining multiple operations. Each step gets its own line, which makes the flow easier to follow.</p>
<p>🎯 Use the pipe across multiple lines to show the first six rows of the <code>mtcars</code> dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span>        <span class="co"># start with data</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()          <span class="co"># show first six rows</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
</div>
<p>✅ Check that this returns the same output as the previous example.</p>
<p>🗣 The line break does not change what the code does. It makes the code easier for a human to read. In longer workflows, each line can show one step in the data process.</p>
<p>🤔 Readability is part of good coding judgment. A short one-line command may be fine for a simple task. A multi-line pipe can be better when the workflow has several steps. Ask yourself: “Would future-me understand this faster if each step had its own line?”</p>
<hr>
<p>To understand how to use the pipe in real data work, you need to learn at least one <code>dplyr</code> verb. Let’s start with <code>select()</code> for choosing columns.</p>
</section>
<section id="selecting-columns" class="level2">
<h2 class="anchored" data-anchor-id="selecting-columns">Selecting Columns</h2>
<p>In Chapter 8, you learned that you can select columns with base R brackets by name, like <code>data[c("col1", "col2")]</code>. With <code>dplyr::select()</code>, you can do the same thing with a more concise syntax.</p>
<p>The <code>dplyr</code> verb <span class="glossary-term" data-term="select()"><code>select()</code></span> returns the same type of data object, keeps all rows, and changes which columns are shown. It can select columns by name, by ranges such as <code>x:y</code>, and by helper patterns.</p>
<p>You can use R operators such as <code>:</code>, <code>!</code>, <code>&amp;</code>, <code>|</code>, <code>c()</code>, and <code>%in%</code> to select columns. You can also use helper functions like <code>starts_with()</code>, <code>ends_with()</code>, <code>contains()</code>, and <code>matches()</code> to select columns based on patterns in their names. <strong>To keep it simple, we will focus on selecting columns by name and by negative selection with <code>-</code>.</strong></p>
<p>📜 The SYNTAX: <code>select(data, col1, col2, …)</code></p>
<section id="positive-selection" class="level3">
<h3 class="anchored" data-anchor-id="positive-selection">Positive Selection</h3>
<p>🎯 Keep specific columns by name.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(mtcars, mpg, cyl, hp)    <span class="co"># keep three columns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  hp
Mazda RX4           21.0   6 110
Mazda RX4 Wag       21.0   6 110
Datsun 710          22.8   4  93
Hornet 4 Drive      21.4   6 110
Hornet Sportabout   18.7   8 175
Valiant             18.1   6 105
Duster 360          14.3   8 245
Merc 240D           24.4   4  62
Merc 230            22.8   4  95
Merc 280            19.2   6 123
Merc 280C           17.8   6 123
Merc 450SE          16.4   8 180
Merc 450SL          17.3   8 180
Merc 450SLC         15.2   8 180
Cadillac Fleetwood  10.4   8 205
Lincoln Continental 10.4   8 215
Chrysler Imperial   14.7   8 230
Fiat 128            32.4   4  66
Honda Civic         30.4   4  52
Toyota Corolla      33.9   4  65
Toyota Corona       21.5   4  97
Dodge Challenger    15.5   8 150
AMC Javelin         15.2   8 150
Camaro Z28          13.3   8 245
Pontiac Firebird    19.2   8 175
Fiat X1-9           27.3   4  66
Porsche 914-2       26.0   4  91
Lotus Europa        30.4   4 113
Ford Pantera L      15.8   8 264
Ferrari Dino        19.7   6 175
Maserati Bora       15.0   8 335
Volvo 142E          21.4   4 109</code></pre>
</div>
</div>
<p>✅ Check that the output keeps all rows but only shows the <code>mpg</code>, <code>cyl</code>, and <code>hp</code> columns.</p>
<p>🗣 The <code>select()</code> function keeps only the <code>mpg</code>, <code>cyl</code>, and <code>hp</code> columns from the <code>mtcars</code> dataset. The resulting data frame contains all rows but only those three columns.</p>
<p>🤔 This is a method-choice moment. Base R brackets (Chapter 10) and <code>select()</code> can both choose columns. Ask yourself: “Which version makes the column choices easier to read?”</p>
</section>
<section id="negative-selection" class="level3">
<h3 class="anchored" data-anchor-id="negative-selection">Negative Selection</h3>
<p>In Chapter 10, you learned that <code>x[-i, -j]</code> can drop the i-th row and j-th column. In <code>dplyr::select()</code>, you can use a leading <code>-</code> to drop columns by name.</p>
<p>🎯 Remove columns with a leading <code>-</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(mtcars, <span class="sc">-</span>gear)   <span class="co"># drop one column</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  disp  hp drat    wt  qsec vs am carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    4
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    2
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    2
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    2
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    4
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    6
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    8
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    2</code></pre>
</div>
</div>
<p>✅ Check that the output keeps all rows and removes only the <code>gear</code> column.</p>
<p>🗣 The <code>select()</code> function drops the <code>gear</code> column from the <code>mtcars</code> dataset. The resulting data frame contains all rows and all columns except for <code>gear</code>.</p>
<p>🤔 Sometimes it is clearer to say what you do not want instead of listing everything you want to keep. Ask yourself: “Is excluding this column clearer than naming all the columns I want?”</p>
<hr>
<p>Now that you know how to select columns, let’s see how to use the pipe to chain operations together.</p>
</section>
<section id="piping-with-select" class="level3">
<h3 class="anchored" data-anchor-id="piping-with-select">Piping with Select</h3>
<p>🎯 Add a pipe.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mpg, cyl, hp)   <span class="co"># easier to read?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  hp
Mazda RX4           21.0   6 110
Mazda RX4 Wag       21.0   6 110
Datsun 710          22.8   4  93
Hornet 4 Drive      21.4   6 110
Hornet Sportabout   18.7   8 175
Valiant             18.1   6 105
Duster 360          14.3   8 245
Merc 240D           24.4   4  62
Merc 230            22.8   4  95
Merc 280            19.2   6 123
Merc 280C           17.8   6 123
Merc 450SE          16.4   8 180
Merc 450SL          17.3   8 180
Merc 450SLC         15.2   8 180
Cadillac Fleetwood  10.4   8 205
Lincoln Continental 10.4   8 215
Chrysler Imperial   14.7   8 230
Fiat 128            32.4   4  66
Honda Civic         30.4   4  52
Toyota Corolla      33.9   4  65
Toyota Corona       21.5   4  97
Dodge Challenger    15.5   8 150
AMC Javelin         15.2   8 150
Camaro Z28          13.3   8 245
Pontiac Firebird    19.2   8 175
Fiat X1-9           27.3   4  66
Porsche 914-2       26.0   4  91
Lotus Europa        30.4   4 113
Ford Pantera L      15.8   8 264
Ferrari Dino        19.7   6 175
Maserati Bora       15.0   8 335
Volvo 142E          21.4   4 109</code></pre>
</div>
</div>
<p>✅ Check that this returns the same columns as the earlier <code>select(mtcars, mpg, cyl, hp)</code> example.</p>
<p>🗣 The pipe <code>%&gt;%</code> takes the <code>mtcars</code> dataset and feeds it into the <code>select()</code> function, which keeps only the <code>mpg</code>, <code>cyl</code>, and <code>hp</code> columns. This version reads more like a sequence of actions: start with <code>mtcars</code>, and then select these columns.</p>
<p>🤔 The result is the same, but the reading direction is different. Ask yourself: “Do I prefer seeing the dataset inside the function, or starting with the dataset and moving step by step?”</p>
<hr>
<p>Now that you can select columns and use the pipe, let’s practice storing a subset of a dataset in the environment.</p>
</section>
<section id="subset-with-select" class="level3">
<h3 class="anchored" data-anchor-id="subset-with-select">Subset with Select</h3>
<p>We’ll mix it up by using a different dataset, 🌐 <code>gapminder</code> from <code>dslabs</code>. This dataset contains information about countries over time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>?gapminder</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🎯 Create a copy of the <code>gapminder</code> dataset that contains only specific columns: <code>country</code>, <code>year</code>, <code>infant_mortality</code>, and <code>continent</code>. Name the subset <code>I_Demo</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>I_Demo <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, year, infant_mortality, continent)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(I_Demo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              country year infant_mortality continent
1             Albania 1960           115.40    Europe
2             Algeria 1960           148.20    Africa
3              Angola 1960           208.00    Africa
4 Antigua and Barbuda 1960               NA  Americas
5           Argentina 1960            59.87  Americas
6             Armenia 1960               NA      Asia</code></pre>
</div>
</div>
<p>✅ Check that <code>I_Demo</code> contains the columns <code>country</code>, <code>year</code>, <code>infant_mortality</code>, and <code>continent</code>.</p>
<p>🗣 A new dataset called <code>I_Demo</code> was created from the <code>gapminder</code> dataset. It contains all rows from <code>gapminder</code>, but only the columns <code>country</code>, <code>year</code>, <code>infant_mortality</code>, and <code>continent</code>.</p>
<p>🤔 Creating a smaller dataset is a choice about focus. Ask yourself: “Which columns do I need for the question I am trying to answer, and which columns would only distract me?”</p>
<hr>
<p>✍️ Practice: fill in the blank prompt</p>
<p>You try to design your own subsetting operation.</p>
<p>🎯 Write an example that selects only the columns you choose.</p>
<p><strong>Step 1</strong> Identify the column options.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Pre-check</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(gapminder)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "country"          "year"             "infant_mortality" "life_expectancy" 
[5] "fertility"        "population"       "gdp"              "continent"       
[9] "region"          </code></pre>
</div>
</div>
<p><strong>Step 2</strong> Choose which columns to keep and write the code to create a new dataset with only those columns. Use the exact names of the columns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>Your_Choice <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(____, ____, ____)   <span class="co"># choose columns</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Your_Choice)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Your new dataset should keep all rows from <code>gapminder</code> but only show the columns you selected.</p>
<hr>
<p>Now that you know how to store a subset when selecting columns and use the pipe, let’s see how to filter rows with <code>filter()</code>.</p>
</section>
</section>
<section id="filtering-rows" class="level2">
<h2 class="anchored" data-anchor-id="filtering-rows">Filtering Rows</h2>
<p>In chapter 8 and 10, you learned that you can filter rows with base R brackets by name, like <code>data[data$col1 &gt; 10, ]</code>. With <code>dplyr::filter()</code>, you can do the same thing but with a more concise syntax.</p>
<p><span class="glossary-term" data-term="filter()"><code>filter()</code></span> keeps only rows for which the condition is <code>TRUE</code>. This means that <code>filter()</code> treats <code>NA</code> values as <code>FALSE</code> and drops them. If you want to keep rows with <code>NA</code>, you can use the <code>is.na()</code> function in your filter condition.</p>
<p>📜 The SYNTAX: <code>filter(data, condition1, condition2, …)</code></p>
<p>You’ll often use <span class="glossary-term" data-term="Logical Operators">logical operators</span> with <code>filter()</code>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Operator</th>
<th>Meaning</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>&gt;</code></td>
<td>greater than</td>
<td>mpg <strong><code>&gt;</code></strong> 20</td>
</tr>
<tr class="even">
<td><code>&lt;</code></td>
<td>less than</td>
<td>mpg <strong><code>&lt;</code></strong> 15</td>
</tr>
<tr class="odd">
<td><code>==</code></td>
<td>equal to</td>
<td>am <strong><code>==</code></strong> 1</td>
</tr>
<tr class="even">
<td><code>&gt;=</code></td>
<td>greater <em>or</em> equal</td>
<td>mpg <strong><code>&gt;=</code></strong> 25</td>
</tr>
<tr class="odd">
<td><code>&lt;=</code></td>
<td>less <em>or</em> equal</td>
<td>mpg <strong><code>&lt;=</code></strong> 15</td>
</tr>
<tr class="even">
<td><code>!</code></td>
<td>not</td>
<td><strong><code>!</code></strong>(gear %in% c(3,4))</td>
</tr>
<tr class="odd">
<td><code>!=</code></td>
<td>not equal to</td>
<td>gear <strong><code>!=</code></strong> 4</td>
</tr>
<tr class="even">
<td><code>&amp;</code></td>
<td>and</td>
<td>x &gt; 2 <strong><code>&amp;</code></strong> y == “a”</td>
</tr>
<tr class="odd">
<td><code>|</code></td>
<td>or</td>
<td>cyl == 4 <strong><code>|</code></strong> cyl == 8</td>
</tr>
<tr class="even">
<td><code>%in%</code></td>
<td>in set</td>
<td>region <strong><code>%in%</code></strong> c(“West”, “South”)</td>
</tr>
</tbody>
</table>
<p>Let’s start with a simple example of filtering rows with a single condition.</p>
<section id="single-condition" class="level3">
<h3 class="anchored" data-anchor-id="single-condition">Single Condition</h3>
<p>🎯 <code>filter()</code> uses logical operators!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(mtcars, mpg <span class="sc">&gt;=</span> <span class="dv">25</span>)               <span class="co"># high‑mileage cars</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2</code></pre>
</div>
</div>
<p>✅ Check that every row shown has <code>mpg</code> greater than or equal to 25.</p>
<p>🗣 The <code>filter()</code> function keeps rows where the condition is <code>TRUE</code>. This code keeps cars with <code>mpg &gt;= 25</code> and drops cars that do not meet that condition.</p>
<p>🤔 This is the same row-filtering idea you used with base R brackets, but using a custom function.</p>
</section>
<section id="piping-with-filter" class="level3">
<h3 class="anchored" data-anchor-id="piping-with-filter">Piping with Filter</h3>
<p>We’ll mix it up by using a different data set, 🔫️<code>murders</code> from <code>dslabs</code>. This data set contains information about gun murders in the US.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>?murders</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>💬 Prediction: There are 50 states in the US, so I expect about 50 rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Pre-check</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(murders)  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51</code></pre>
</div>
</div>
<p>🗣 The row count is 51, not 50. That means this dataset includes one place that is not one of the 50 states. ❓ Question: What is the extra place?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#⚡ Test:</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(murders<span class="sc">$</span>state)  <span class="co"># 51 states</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Alabama"              "Alaska"               "Arizona"             
 [4] "Arkansas"             "California"           "Colorado"            
 [7] "Connecticut"          "Delaware"             "District of Columbia"
[10] "Florida"              "Georgia"              "Hawaii"              
[13] "Idaho"                "Illinois"             "Indiana"             
[16] "Iowa"                 "Kansas"               "Kentucky"            
[19] "Louisiana"            "Maine"                "Maryland"            
[22] "Massachusetts"        "Michigan"             "Minnesota"           
[25] "Mississippi"          "Missouri"             "Montana"             
[28] "Nebraska"             "Nevada"               "New Hampshire"       
[31] "New Jersey"           "New Mexico"           "New York"            
[34] "North Carolina"       "North Dakota"         "Ohio"                
[37] "Oklahoma"             "Oregon"               "Pennsylvania"        
[40] "Rhode Island"         "South Carolina"       "South Dakota"        
[43] "Tennessee"            "Texas"                "Utah"                
[46] "Vermont"              "Virginia"             "Washington"          
[49] "West Virginia"        "Wisconsin"            "Wyoming"             </code></pre>
</div>
</div>
<p>🗣 The <code>murders</code> dataset includes the District of Columbia, so the dataset has 51 rows before we remove it.</p>
<p>🎯 Create a copy of the <code>murders</code> dataset that excludes the District of Columbia.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>No_Washington <span class="ot">&lt;-</span> murders <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">!=</span> <span class="st">"District of Columbia"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>✅ Check that <code>No_Washington</code> has 50 rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(No_Washington)  <span class="co"># 50 states</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(No_Washington<span class="sc">$</span>state)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Alabama"        "Alaska"         "Arizona"        "Arkansas"      
 [5] "California"     "Colorado"       "Connecticut"    "Delaware"      
 [9] "Florida"        "Georgia"        "Hawaii"         "Idaho"         
[13] "Illinois"       "Indiana"        "Iowa"           "Kansas"        
[17] "Kentucky"       "Louisiana"      "Maine"          "Maryland"      
[21] "Massachusetts"  "Michigan"       "Minnesota"      "Mississippi"   
[25] "Missouri"       "Montana"        "Nebraska"       "Nevada"        
[29] "New Hampshire"  "New Jersey"     "New Mexico"     "New York"      
[33] "North Carolina" "North Dakota"   "Ohio"           "Oklahoma"      
[37] "Oregon"         "Pennsylvania"   "Rhode Island"   "South Carolina"
[41] "South Dakota"   "Tennessee"      "Texas"          "Utah"          
[45] "Vermont"        "Virginia"       "Washington"     "West Virginia" 
[49] "Wisconsin"      "Wyoming"       </code></pre>
</div>
</div>
<p>🗣 A new dataset called <code>No_Washington</code> was created from the <code>murders</code> dataset that excludes Washington DC.</p>
</section>
<section id="multiple-conditions-and" class="level3">
<h3 class="anchored" data-anchor-id="multiple-conditions-and">Multiple Conditions with AND</h3>
<p>We learned in chapter 8 and 10 that we can filter with multiple conditions using <code>&amp;</code> for AND. In <code>dplyr::filter()</code>, commas (<code>,</code>) equal AND (<code>&amp;</code>).</p>
<section id="and-comma" class="level4">
<h4 class="anchored" data-anchor-id="and-comma">And <code>,</code> and <code>&amp;</code></h4>
<p>Let’s filter with two conditions! In filter(), multiple conditions separated by commas are combined with &amp;. So these two calls mean the same thing:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(mtcars, mpg <span class="sc">&gt;=</span> <span class="dv">25</span>, cyl <span class="sc">==</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(mtcars, mpg <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> cyl <span class="sc">==</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2</code></pre>
</div>
</div>
<p>🗣 Both of these code chunks will return the same result: a subset of the <code>mtcars</code> dataset that includes only rows where <code>mpg</code> is greater than or equal to 25 and <code>cyl</code> is equal to 4. The first chunk uses commas to separate conditions, while the second chunk uses the <code>&amp;</code> operator to combine them. Both are valid ways to specify multiple conditions in <code>filter()</code>.</p>
<p>The catch is that comma is only a shortcut inside <code>filter()</code> for separating multiple conditions. It is not a general replacement for <code>&amp;</code> in R, and it does not help when you need more complex grouping with <code>|</code>.</p>
</section>
<section id="with-the-pipe" class="level4">
<h4 class="anchored" data-anchor-id="with-the-pipe">With the pipe</h4>
<p>🎯 Let’s filter with two conditions with a pipe and store it as <code>efficient</code></p>
<p>❓ Question: How many cars have <em>both</em> mpg ≥ 25 <em>and</em> 4 cylinders?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>efficient <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mpg <span class="sc">&gt;=</span> <span class="dv">25</span>, cyl <span class="sc">==</span> <span class="dv">4</span>)           <span class="co"># two conditions</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>✅ Check that <code>efficient</code> has 6 rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(efficient)  <span class="co"># how many cars are efficient?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>🗣 A new dataset called <code>efficient</code> was created from the <code>mtcars</code> dataset that includes only rows where <code>mpg</code> is greater than or equal to 25 <em>and</em> <code>cyl</code> is equal to 4. The number of rows in the <code>efficient</code> dataset indicates how many cars in the dataset meet <strong>both</strong> conditions (n = 6).</p>
<p>🤔 AND logic is strict. A row must satisfy both conditions to stay. Ask yourself: “Did I mean both conditions at the same time, or did I mean either condition?”</p>
</section>
</section>
<section id="multiple-conditions-or" class="level3">
<h3 class="anchored" data-anchor-id="multiple-conditions-or">Multiple Conditions with OR</h3>
<p>In <code>dplyr::filter()</code>, multiple conditions separated by commas are combined with AND, not OR. So when you want OR logic, you must write <code>|</code> explicitly inside the condition. In base R, <code>|</code> is the elementwise OR operator, and <code>%in%</code> returns <code>TRUE</code> when a value appears in a set of values.</p>
<section id="or-pipe-in" class="level4">
<h4 class="anchored" data-anchor-id="or-pipe-in">Or <code>|</code> and <code>%in%</code></h4>
<p>🎯 Let’s filter with OR! When you want rows that match either one condition or another, use <code>|</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(mtcars, cyl <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span> cyl <span class="sc">==</span> <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710     22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Valiant        18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Merc 240D      24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230       22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280       19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C      17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ferrari Dino   19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(mtcars, cyl <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">6</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710     22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Valiant        18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Merc 240D      24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230       22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280       19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C      17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ferrari Dino   19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
</div>
</div>
<p>🗣 Both of these code chunks return the same result: a subset of the <code>mtcars</code> dataset that includes only rows where <code>cyl</code> is equal to 4 or 6. The first chunk uses the <code>|</code> operator to say “4 cylinders or 6 cylinders.” The second chunk uses <code>%in%</code> to check whether <code>cyl</code> is one of the values in <code>c(4, 6)</code>. Both are valid, but %in% is often easier to read when you are checking one variable against several possible values.</p>
<p>The catch is that <code>%in%</code> is only a shortcut when you are comparing one variable to multiple values. It is not a general replacement for <code>|</code>. For example, if you want cars with 4 cylinders or cars with <code>mpg &gt;= 30</code>, you must use <code>|</code> because those are two different conditions on different variables.</p>
<p>🤔 This is another method-choice decision. <code>|</code> works well when comparing different conditions. <code>%in%</code> is often cleaner when checking whether one variable matches several possible values. Ask yourself: “Am I comparing one variable to a set, or combining different conditions?”</p>
<p>🎯 Let’s filter with OR on different variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(mtcars, cyl <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span> mpg <span class="sc">&gt;=</span> <span class="dv">30</span>)  <span class="co"># different variables</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Datsun 710     22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Merc 240D      24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230       22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
</div>
</div>
<p>✅ Check that this keeps cars that meet at least one condition: 4 cylinders, high mileage, or both.</p>
<p>🗣 This code chunk returns a subset of the <code>mtcars</code> dataset that includes rows where either <code>cyl</code> is equal to 4 or <code>mpg</code> is greater than or equal to 30. Since these conditions involve different variables, you cannot use <code>%in%</code> and must use the <code>|</code> operator to combine them.</p>
</section>
<section id="with-the-pipe-or" class="level4">
<h4 class="anchored" data-anchor-id="with-the-pipe-or">With the pipe</h4>
<p>🎯 Let’s filter with two conditions using OR (<code>|</code>), piping, and storing the subset to the environment.</p>
<p>❓ Question: How many cars have <em>either</em> mpg ≥ 25 <em>or</em> 4 cylinders?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk:</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>efficient_ish <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mpg <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">|</span> cyl <span class="sc">==</span> <span class="dv">4</span>)    <span class="co"># two conditions</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>✅ Check that <code>efficient_ish</code> has 11 rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(efficient_ish)  <span class="co"># how many cars are efficient_ish?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
</div>
<p>🗣 A new dataset called <code>efficient_ish</code> was created from the <code>mtcars</code> dataset that includes rows where either <code>mpg</code> is greater than or equal to 25 or <code>cyl</code> is equal to 4. The number of rows in the <code>efficient_ish</code> dataset indicates how many cars meet <em>at least one</em> of those conditions. (n = 11)</p>
<p>🤔 OR logic is broader than AND logic. A row only needs to satisfy one condition to stay. Ask yourself: “Did my row count get larger because I widened the rule?”</p>
</section>
</section>
</section>
<section id="filter-and-select" class="level2">
<h2 class="anchored" data-anchor-id="filter-and-select">filter() AND select()</h2>
<p>So far, you have used <code>select()</code> to change which columns you keep and <code>filter()</code> to change which rows you keep. Now let’s combine them.</p>
<p>📖 Review</p>
<ul>
<li><code>filter()</code> looks at the values in a data frame and keeps only rows where the condition is <code>TRUE</code>.</li>
<li><code>select()</code> looks at column names and keeps only the variables you ask for.</li>
</ul>
<p>Combining them lets you subset a data frame by both rows and columns.</p>
<p>📜 The SYNTAX:</p>
<p><code>data %&gt;% filter(condition) %&gt;% select(col1, col2, …)</code></p>
<p>A safe beginner workflow habit is to <code>filter()</code> first and <code>select()</code> second. That way, all columns are still available when you write your filtering conditions. If you <code>select()</code> first and accidentally remove a column needed by <code>filter()</code>, your code will fail.</p>
<p>🤔 This is a workflow-order choice. Both <code>filter()</code> and <code>select()</code> are useful, but the order matters when one step depends on a column that might disappear. Ask yourself: “Which columns do I still need for the next step?”</p>
<p>We’ll mix it up by using a different dataset, ☣️ <code>us_contagious_diseases</code> from <code>dslabs</code>. This dataset contains information about contagious diseases in the US.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>?us_contagious_diseases</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🎯 Using <code>us_contagious_diseases</code> from <code>dslabs</code>, keep only rows for <code>Alaska</code> from <code>1980</code> and later. Then keep only the columns <code>year</code>, <code>disease</code>, and <code>count</code>. Store the result as <code>alaska_disease</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>alaska_disease <span class="ot">&lt;-</span> us_contagious_diseases <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"Alaska"</span>, year <span class="sc">&gt;=</span> <span class="dv">1980</span>) <span class="sc">%&gt;%</span>   <span class="co"># rows</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, disease, count)                  <span class="co"># columns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 This pipeline says: start with <code>us_contagious_diseases</code>, keep only the rows for Alaska in 1980 or later, and then trim the result down to three columns. <code>filter()</code> changes the number of rows. <code>select()</code> changes the number of columns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(alaska_disease)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year     disease count
1 1980 Hepatitis A    18
2 1981 Hepatitis A    45
3 1982 Hepatitis A    17
4 1983 Hepatitis A    43
5 1984 Hepatitis A    14
6 1985 Hepatitis A    18</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(alaska_disease)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "year"    "disease" "count"  </code></pre>
</div>
</div>
<p>✅ Check that <code>alaska_disease</code> only shows the columns <code>year</code>, <code>disease</code>, and <code>count</code>.</p>
<p>🗣 A new dataset called <code>alaska_disease</code> was created from <code>us_contagious_diseases</code>. First, <code>filter()</code> kept only rows where <code>state</code> is <code>"Alaska"</code> and <code>year</code> is greater than or equal to <code>1980</code>. Then, <code>select()</code> kept only the columns <code>year</code>, <code>disease</code>, and <code>count</code>. Notice that <code>state</code> was used in the filtering step, but it does not appear in the final result because <code>select()</code> removed it afterward.</p>
<p>🤔 This is why order matters. If you had selected only <code>year</code>, <code>disease</code>, and <code>count</code> first, the <code>state</code> column would not be available for filtering. Ask yourself: “Did I remove a column before I was done using it?”</p>
</section>
<section id="one-application" class="level2">
<h2 class="anchored" data-anchor-id="one-application">One Application</h2>
<p>❓ Which automatic cars (<code>am == 0</code>) in <code>mtcars</code> have horsepower greater than 150?</p>
<p>In <code>mtcars</code>, <code>am</code> is coded as <code>0 = automatic</code> and <code>1 = manual</code>. Horsepower is stored in <code>hp</code>, and miles per gallon is stored in <code>mpg</code>.</p>
<p>🎯 Answer the question. Show only <code>hp</code> and <code>mpg</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>powerful_auto <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(am <span class="sc">==</span> <span class="dv">0</span>, hp <span class="sc">&gt;</span> <span class="dv">150</span>) <span class="sc">%&gt;%</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(hp, mpg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(powerful_auto)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    hp  mpg
Hornet Sportabout  175 18.7
Duster 360         245 14.3
Merc 450SE         180 16.4
Merc 450SL         180 17.3
Merc 450SLC        180 15.2
Cadillac Fleetwood 205 10.4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(powerful_auto)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
</div>
<p>✅ Check that <code>powerful_auto</code> contains 10 rows.</p>
<p>🗣 A new dataset called <code>powerful_auto</code> was created from <code>mtcars</code>. The <code>filter()</code> step kept only cars that are automatic (<code>am == 0</code>) and have more than 150 horsepower. The <code>select()</code> step then kept only the <code>hp</code> and <code>mpg</code> columns because those are the variables needed for the report. The result contains 10 cars.</p>
<p>🤔 Open-minded coding means checking whether your workflow matches the question. This pipeline filters with columns that explain the rule, then selects the columns needed for the final answer. Ask yourself: “Does my final dataset show enough information to answer the question clearly?”</p>
<hr>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In Chapter 11, you learned how to use <code>dplyr</code> to create smaller, analysis-ready datasets in a clear and reproducible way. You practiced <code>select()</code> to keep or drop columns, <code>filter()</code> to keep rows based on logical conditions, and <code>%&gt;%</code> to connect multiple steps into a readable workflow. You also worked in Quarto so that your code, output, and written notes stay together in one document.</p>
<p>You applied comparison operators and Boolean logic to ask more precise questions of data, including single-condition filters, multiple-condition filters with AND/OR logic, and workflows that combine <code>filter()</code> and <code>select()</code> in the same pipeline. You also practiced previewing results, checking row counts, and creating focused subsets from real datasets for exploration and reporting.</p>
<p>The larger learning goal is method judgment. Base R brackets and <code>dplyr</code> verbs can often answer the same question, but they make different parts of the work easier to see. Open-minded coding means comparing reasonable approaches, verifying the result, and choosing the method that makes your logic easiest to read and explain.</p>
</section>
<section id="chapter-terms" class="level2">
<h2 class="anchored" data-anchor-id="chapter-terms">Chapter Terms</h2>
<p><strong>dplyr</strong>: An R package in the tidyverse that provides readable data-wrangling verbs for working with data frames. In this chapter, <code>dplyr</code> is used to select columns, filter rows, and build clear subsetting workflows.</p>
<p><strong><code>filter()</code></strong>: A <code>dplyr</code> function used to keep rows from a data frame or tibble based on one or more logical conditions. <code>filter()</code> keeps observations where the condition evaluates to <code>TRUE</code> and drops rows where the condition evaluates to <code>FALSE</code>.</p>
<p><strong>Logical Operators</strong>: Operators that create or combine logical elements. The most common are comparison operators—<code>==</code>, <code>!=</code>, <code>&lt;</code>, <code>&gt;</code>, <code>&lt;=</code>, <code>&gt;=</code>—which return <code>TRUE</code>/<code>FALSE</code>, and Boolean operators—<code>!</code> (NOT), <code>&amp;</code> / <code>|</code> (AND/OR applied element-by-element), and <code>&amp;&amp;</code> / <code>||</code> (AND/OR that evaluate only the first element, mainly for if conditions).</p>
<p><strong>Pipe</strong>: An operator that passes the result of one step directly into the next step, letting you write code as a readable sequence of actions instead of nesting functions inside each other. In tidyverse code, the pipe is usually <code>%&gt;%</code>, so <code>x %&gt;% f()</code> means “take <code>x</code>, then apply <code>f()</code>”; in newer base R, a similar built-in pipe is <code>|&gt;</code>.</p>
<p><strong>Render</strong>: To process a Quarto document and create an output file, such as an HTML report. Rendering runs the document’s code as needed, combines the code results with the written text, and checks whether the document can be rebuilt as a reproducible report.</p>
<p><strong><code>select()</code></strong>: A <code>dplyr</code> function used to choose columns from a data frame or tibble. <code>select()</code> keeps all rows but lets you keep, reorder, rename, or drop variables by column name or selection helper.</p>
<p><strong>Tidyverse</strong>: An opinionated collection of R packages designed to work together for data science. The packages share a common design philosophy, data structures, and coding style, which makes it easier to import, clean, reshape, visualize, and analyze data within a consistent workflow.</p>
<p><strong>Quarto</strong>: An open-source scientific and technical publishing system that uses Quarto Markdown files (<code>.qmd</code>) to combine Markdown text with executable code (including R) and render reproducible outputs like HTML, PDF, Word, slides, and websites. It’s the language-agnostic successor to R Markdown, designed for reports where code, results, and writing stay tied together.</p>
<p><strong>Verbs</strong>: The main data-wrangling functions in <code>dplyr</code>, named for the actions they perform on a data frame or tibble. Common <code>dplyr</code> verbs include <code>filter()</code> to keep rows, <code>select()</code> to choose columns, <code>mutate()</code> to create or change variables, <code>summarise()</code> to calculate summaries, and <code>arrange()</code> to reorder rows.</p>
<p><strong>YAML Header</strong>: The metadata section at the top of an R Markdown or Quarto document, written between <code>---</code> lines, that controls document settings like the title, author, date, output format (HTML/PDF/Word), and options for rendering.</p>
</section>
<section id="practice-space" class="level2">
<h2 class="anchored" data-anchor-id="practice-space">📝 Practice Space</h2>
<p>In this Practice Space, you will use <code>dplyr::select()</code>, <code>dplyr::filter()</code>, and the pipe <code>%&gt;%</code> to create smaller, focused datasets. You will also keep practicing Quarto as a reproducible workspace for code, output, and memo notes.</p>
<p>Create a new Quarto document and save it in your course folder as:</p>
<p><code>chapter11_practice.qmd</code></p>
<p>Before you begin:</p>
<ol type="1">
<li>Create a new Quarto document in RStudio.</li>
<li>Save it as <code>chapter11_practice.qmd</code>.</li>
<li>Edit the YAML so it includes the title <code>"Chapter 11 Practice"</code>, your name, the date, and HTML output.</li>
<li>Delete the default body text below the YAML.</li>
<li>Create headings for each task using <code>## Task 0</code>, <code>## Task 1</code>, and so on.</li>
</ol>
<p>Complete each task in order. Fill in the blanks, run your code, and add short memo notes as you work.</p>
<p>In this Practice Space, you will see three memo prompts:</p>
<ul>
<li>🎯 <strong>Write the goal</strong> state the coding directions in your own words.</li>
<li>🗣 <strong>Add Comments:</strong> explain what the code or output shows.</li>
<li>🪞 <strong>Reflect:</strong> explain your thinking, what you checked, what changed, or what you would try next.</li>
</ul>
<p>Each task should include at least one memo response. You do not need to answer every prompt perfectly. The goal is to practice documenting your thinking while you work.</p>
<p><strong>Open-mindedness</strong> memos means documenting comparing reasonable methods, and choosing the approach that makes the code easiest to read, check, and explain. If you encounter an error, document your <strong>tenacity</strong> by briefly noting what happened, what you tried, and how you fixed it or what still confuses you. Document how you troubleshot the error and what resource(s) you used to help you resolve the issue (<strong>transparency</strong>). Show <strong>courage</strong> by sharing your thinking process, even if it includes mistakes or confusion.</p>
<p>If you get stuck, briefly document what happened, what you tried, and what still confuses you.</p>
<p>You may quote AI output only when you clearly mark it as quoted text, either with quotation marks or a block quote using <code>&gt;</code>. Then hand-type your own explanation of why you are including the quote.</p>
<p>Before you submit, clear your Environment and run the <code>.qmd</code> from top to bottom. Your file should run without errors and create the required objects listed in Task 7.</p>
<p>For this assignment, submit the saved <code>.qmd</code> file. You do not need to submit a rendered HTML file.</p>
<section id="task-0" class="level3">
<h3 class="anchored" data-anchor-id="task-0">Task 0</h3>
<p>📦 Load the packages needed for this Practice Space: <code>dplyr</code> and <code>dslabs</code>. This setup chunk is also a good place to practice Quarto chunk controls like <code>#| message: false</code> and <code>#| warning: false</code>.</p>
<p>🎯 Write the goal of this task in your own words.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk, fill in the blanks</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">_______</span>(dslabs)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="fu">_______</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Add Comments: Explain why <code>library()</code> needs to run when you start a new R session, even if the package was already installed earlier.</p>
<p>🪞 Reflect: Quarto lets you choose whether messages and warnings appear in the rendered report. When might it be useful to show messages while learning? When might it be useful to hide them in a cleaner final report?</p>
<p>💡 <strong>Tip:</strong> Open-mindedness in this chapter means comparing reasonable options and choosing the one that makes your workflow easier to read, check, and explain.</p>
</section>
<section id="task-1" class="level3">
<h3 class="anchored" data-anchor-id="task-1">Task 1</h3>
<p><strong>Column Selection</strong></p>
<p>📝 Create <strong><code>C_Overload</code></strong> that keeps only <code>year</code> and <code>carbon_emissions</code> from the 🌡️ <code>temp_carbon</code> data frame. Use <code>select()</code> without <code>%&gt;%</code>.</p>
<p>🎯 Write the goal of this task in your own words.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk, fill in the blanks</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>C_Overload <span class="ot">&lt;-</span> <span class="fu">_______</span>(_______, year, _______)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(C_Overload)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Add Comments: Explain what <code>select()</code> did in this task. How does <code>head()</code> help you check that it worked?</p>
<p>🪞 Reflect: In Chapter 10, you used base R brackets to choose columns. In this task, you used <code>select()</code> without a pipe. Which version feels easier to read for this task, and what output helps you verify that only the intended columns were kept?</p>
</section>
<section id="task-2" class="level3">
<h3 class="anchored" data-anchor-id="task-2">Task 2</h3>
<p><strong>Single-Column Dataframe</strong></p>
<p>Pipe the 🌟 <code>stars</code> dataset in <code>dslabs</code> through <code>select()</code> to keep only the <code>star</code> column. Name the result <strong><code>star_names</code></strong>.</p>
<p>🎯 Write the goal of this task in your own words.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk, fill in the blanks</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>star_names <span class="ot">&lt;-</span> _______ _______ <span class="fu">_______</span>(star)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(star_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Add Comments: Does this return a vector or keep a one-column data frame? Explain how you can tell from the output.</p>
<p>🪞 Reflect: A one-column data frame and a vector can look similar at first. Why does it matter to stay open to that difference instead of assuming they are the same kind of object?</p>
</section>
<section id="task-3" class="level3">
<h3 class="anchored" data-anchor-id="task-3">Task 3</h3>
<p><strong>Row Filtering</strong></p>
<p>From 🔫 <code>murders</code>, remove every row where <code>state</code> equals <code>"Florida"</code> using <code>!=</code>. Name the object <strong><code>No_Florida</code></strong>.</p>
<p>🎯 Write the goal of this task in your own words.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Pre-test</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(murders<span class="sc">$</span>state)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk, fill in the blanks</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>No_Florida <span class="ot">&lt;-</span> _______ _______ <span class="fu">filter</span>(state _______ <span class="st">"Florida"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(No_Florida<span class="sc">$</span>state)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Add Comments: Explain why pre-checking the unique values of <code>state</code> is useful. What change are you expecting to see in the ✅ Verify step? Explain what rows are removed.</p>
<p>🪞 Reflect: You could have assumed <code>"Florida"</code> appeared exactly as expected, but you checked the available values first. How did that pre-check help you avoid guessing? If <code>"Florida"</code> still appeared in the verification output, what would you check next?</p>
</section>
<section id="task-4" class="level3">
<h3 class="anchored" data-anchor-id="task-4">Task 4</h3>
<p><strong>Multiple Conditions</strong></p>
<p>🚗 From <code>mtcars</code>, use <code>filter()</code> and piping to pull cars that are <strong>manual</strong>, have <code>8</code> <strong>cylinders</strong>, and have <strong>1/4 mile time</strong> less than <code>15</code>. Store the result as <strong><code>Fast_n_Furious</code></strong>.</p>
<p><em>Hint: use <code>?mtcars</code> to identify the relevant variables for each condition.</em></p>
<p>🎯 Write the goal of this task in your own words.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mtcars<span class="sc">$</span>qsec)  <span class="co"># check qsec range</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk, fill in the blanks</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>Fast_n_Furious <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">_______</span>(am <span class="sc">==</span> _______, </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>          cyl <span class="sc">==</span> <span class="dv">8</span>, _______ <span class="sc">&lt;</span> _______)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Fast_n_Furious)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(Fast_n_Furious)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Add Comments: Explain the conditions you used to filter the rows. What does each condition mean in terms of the characteristics of the cars? How many cars meet all three conditions?</p>
<p>🪞 Reflect: This task uses AND logic, so a car must meet all three conditions to stay in the dataset. If your result had more or fewer rows than expected, which condition would you check first, and why?</p>
</section>
<section id="task-5" class="level3">
<h3 class="anchored" data-anchor-id="task-5">Task 5</h3>
<p><strong>OR Logic + Column Slice</strong></p>
<p>From 🚗 <code>mtcars</code>, keep only the cars whose displacement is either <strong>under 160</strong> or <strong>over 250</strong>, and then show only the first three columns of those rows. Store the result as <strong><code>filtered_cars</code></strong>.</p>
<p><em>Hint: use <code>:</code> when selecting the first three columns.</em></p>
<p>🎯 Write the goal of this task in your own words.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Pre-check</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(mtcars<span class="sc">$</span>disp)  <span class="co"># check disp range</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Add Comments: Explain how <code>range(mtcars$disp)</code> helps you decide whether the cutoffs <code>160</code> and <code>250</code> make sense.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Type this in a Quarto code chunk, fill in the blanks</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>filtered_cars <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">_______</span>(disp <span class="sc">&gt;</span> <span class="dv">250</span> _______ disp <span class="sc">&lt;</span> <span class="dv">160</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">_______</span>(_______)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Verify</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(filtered_cars<span class="sc">$</span>disp <span class="sc">&gt;</span> <span class="dv">250</span> <span class="sc">|</span> filtered_cars<span class="sc">$</span>disp <span class="sc">&lt;</span> <span class="dv">160</span>) <span class="co"># check disp condition</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Add Comments: Explain what <code>all()</code> is testing here. What does <code>TRUE</code> tell you about the rows kept in <code>filtered_cars</code>?</p>
<p>🪞 Reflect: This task uses OR logic, so a car can stay if it meets either displacement condition. Why is <code>|</code> the right choice here instead of <code>&amp;</code>? How does <code>all()</code> help you test whether your first filtering idea worked?</p>
</section>
<section id="task-6" class="level3">
<h3 class="anchored" data-anchor-id="task-6">Task 6</h3>
<p><strong>Reflection</strong></p>
<p>📝 Write a few sentences comparing base R brackets <code>[ ]</code>, <code>select()</code>, and <code>filter()</code> for subsetting.</p>
<p>🗣 Add Comments: Explain which method felt easiest to read and which method felt easiest to verify. Use at least one example from this Practice Space.</p>
<p>🪞 Reflect: Open-minded coding does not mean every method is equally good. It means comparing reasonable options and choosing the one that makes the logic clearest for the task. After this chapter, when would you choose base R brackets? When would you choose <code>dplyr</code> verbs?</p>
</section>
<section id="task-7" class="level3">
<h3 class="anchored" data-anchor-id="task-7">Task 7</h3>
<p><strong>Self-check checklist</strong></p>
<p>For the file submission, make sure your <code>.qmd</code> runs from top to bottom without errors and that the following objects are created in your environment with the expected content:</p>
<ul>
<li><p><code>C_Overload</code> exists and has only <code>year</code> and <code>carbon_emissions</code>.</p></li>
<li><p><code>star_names</code> exists and has one column named <code>star</code>.</p></li>
<li><p><code>No_Florida</code> has 0 rows with <code>state == "Florida"</code>.</p></li>
<li><p><code>Fast_n_Furious</code> has rows that only contain manual cars with 8 cylinders where <code>qsec &lt; 15</code>.</p></li>
<li><p><code>filtered_cars</code> has rows where <code>disp &gt; 250</code> OR <code>disp &lt; 160</code> and only the first three columns.</p></li>
<li><p><strong>All code in your Quarto document runs top-to-bottom without errors.</strong></p></li>
</ul>
<p>🎯 Check your <code>.qmd</code> for submission quality.</p>
<p><strong>Step 1: Sweep your Environment (start clean).</strong> Click the 🧹 <strong>broom icon</strong> in the Environment pane to clear objects.</p>
<p><strong>Step 2: Run everything top-to-bottom.</strong> Use <strong>Run → Run All</strong> to execute every chunk in order.</p>
<p><strong>Step 3: Verify the required objects.</strong> Use the checklist above to confirm that each object exists and contains the expected rows and columns.</p>
<p><strong>Step 4: Save and submit.</strong> After your Quarto document runs without errors, make sure your latest edits are saved. Submit the required <code>.qmd</code> file as directed in Canvas.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/lorrainegaudio\.github\.io\/guided-activities-for-learning-R-workflow\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/05-openmindedness/ch10-and-or-in.html" class="pagination-link" aria-label="Chapter 10: And, Or, and Membership">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Chapter 10: And, Or, and Membership</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/06-curiosity/curiosity.html" class="pagination-link" aria-label="Curiosity">
        <span class="nav-page-text">Curiosity</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Goal, Code, Verify, Reflect</p>
</div>   
    <div class="nav-footer-center">
<p>Boise State University</p>
</div>
    <div class="nav-footer-right">
<p><a href="mailto:lorrainegaudio@boisestate.edu">lorrainegaudio@boisestate.edu</a></p>
</div>
  </div>
</footer>
<script>
document.addEventListener("DOMContentLoaded", function () {
  if (typeof bootstrap === "undefined") return;

  function normalizeTerm(text) {
    return String(text || "")
      .toLowerCase()
      .replace(/[’']/g, "")
      .replace(/[^a-z0-9]+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function getDefinitionNodes(chapterTermsContainer) {
    const nodes = [];

    if (!chapterTermsContainer) return nodes;

    /*
      Quarto often places the id on a <section>, not directly on the heading.
      In that case, the term paragraphs are children inside the section.
    */
    if (chapterTermsContainer.tagName === "SECTION") {
      Array.from(chapterTermsContainer.children).forEach(function (child) {
        if (child.matches("p, li")) {
          nodes.push(child);
        }
      });

      return nodes;
    }

    /*
      Fallback: if the id is on the heading itself, collect paragraphs
      after the heading until the next major section.
    */
    let node = chapterTermsContainer.nextElementSibling;

    while (node && !["H1", "H2"].includes(node.tagName)) {
      if (node.matches && node.matches("p, li")) {
        nodes.push(node);
      }

      node = node.nextElementSibling;
    }

    return nodes;
  }

  function getChapterTerms() {
    const terms = new Map();
    const chapterTermsContainer = document.getElementById("chapter-terms");
    const definitionNodes = getDefinitionNodes(chapterTermsContainer);

    definitionNodes.forEach(function (node) {
      const strong = node.querySelector("strong");
      if (!strong) return;

      const fullText = node.textContent.replace(/\s+/g, " ").trim();
      const strongTerm = strong.textContent.replace(/\s+/g, " ").trim();
      const colonIndex = fullText.indexOf(":");

      if (colonIndex === -1) return;

      const fullTerm = fullText.slice(0, colonIndex).trim();
      const definition = fullText.slice(colonIndex + 1).trim();

      if (!strongTerm || !definition) return;

      const entry = {
        title: fullTerm,
        definition: definition
      };

      terms.set(normalizeTerm(strongTerm), entry);
      terms.set(normalizeTerm(fullTerm), entry);
    });

    return terms;
  }

  const chapterTerms = getChapterTerms();

  document.querySelectorAll(".glossary-term").forEach(function (termElement) {
    const dataTerm = termElement.getAttribute("data-term");
    const requestedTerm = dataTerm && dataTerm.trim()
      ? dataTerm.trim()
      : termElement.textContent.trim();

    const glossaryEntry = chapterTerms.get(normalizeTerm(requestedTerm));

    if (!glossaryEntry) {
      termElement.classList.add("glossary-term-missing");
      termElement.setAttribute("title", "Definition not found in Chapter Terms.");
      console.warn("Glossary definition not found for:", requestedTerm);
      return;
    }

    termElement.setAttribute("tabindex", "0");
    termElement.setAttribute("role", "button");
    termElement.setAttribute("data-bs-toggle", "popover");
    termElement.setAttribute("data-bs-trigger", "hover focus");
    termElement.setAttribute("data-bs-placement", "auto");
    termElement.setAttribute("data-bs-title", glossaryEntry.title);
    termElement.setAttribute("data-bs-content", glossaryEntry.definition);

    const existingPopover = bootstrap.Popover.getInstance(termElement);
    if (existingPopover) {
      existingPopover.dispose();
    }

    new bootstrap.Popover(termElement, {
      container: "body",
      html: false,
      customClass: "glossary-popover"
    });
  });
});
</script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>