<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 15: Probability functions – Introduction to R Programming: Goal, Code, Verify, Reflect</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/07-thoroughness/ch16-ggplot2.html" rel="next">
<link href="../../chapters/07-thoroughness/thoroughness.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-30a6f3117ec04dc5da00a6077361ea08.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4a48981ed7de43aebb597d4e7fd5f8e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/07-thoroughness/thoroughness.html">Thoroughness</a></li><li class="breadcrumb-item"><a href="../../chapters/07-thoroughness/ch15-probability-functions.html"><span class="chapter-title">Chapter 15: Probability functions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Introduction to R Programming: Goal, Code, Verify, Reflect</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lorrainegaudio/guided-activities-for-learning-R-workflow" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../front-matter/preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/01-tenacity/tenacity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tenacity</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-tenacity/ch01-navigation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 1: Navigation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-tenacity/ch02-scripts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 2: Scripts</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/02-transparency/transparency.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transparency</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-transparency/ch03-vectors.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 3: Vector</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-transparency/ch04-structures.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 4:️ Structuers</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/03-courage/courage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Courage</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-courage/ch05-help.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 5 Help!</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-courage/ch05-help-prompting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 5 Help! Prompting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-courage/ch06-missing-values.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 6: Missing Values</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/04-autonomy/autonomy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Autonomy</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/04-autonomy/ch07-importing-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 7: Importing Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/04-autonomy/ch08-indexing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 8: Indexing</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/05-openmindedness/openmindedness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Openmindedness</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/05-openmindedness/ch09-github.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 9: Git and GitHub</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/05-openmindedness/ch10-and-or-in.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 10: And, Or, and Membership</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/05-openmindedness/ch11-dplyr-subsetting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 11: dplyr Subsetting</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/06-curiosity/curiosity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Curiosity</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/06-curiosity/ch12-recoding.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 12: Recoding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/06-curiosity/ch13-grouped-summaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 13: Grouped Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/06-curiosity/ch14-chaining.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 14: Chaining</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/07-thoroughness/thoroughness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thoroughness</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/07-thoroughness/ch15-probability-functions.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Chapter 15: Probability functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/07-thoroughness/ch16-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 16: ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/07-thoroughness/ch17-string-detect.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 17: String Detect</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setting Up Your Notes</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">📦 Packages</a></li>
  </ul></li>
  <li><a href="#distribution" id="toc-distribution" class="nav-link" data-scroll-target="#distribution">Distribution of Sums</a></li>
  <li><a href="#warmup" id="toc-warmup" class="nav-link" data-scroll-target="#warmup">Warm‑Up</a></li>
  <li><a href="#simulating" id="toc-simulating" class="nav-link" data-scroll-target="#simulating">Simulating</a>
  <ul class="collapse">
  <li><a href="#coin-flips" id="toc-coin-flips" class="nav-link" data-scroll-target="#coin-flips">🪙 Coin Flips</a></li>
  <li><a href="#dice-rolls" id="toc-dice-rolls" class="nav-link" data-scroll-target="#dice-rolls">🎲 Dice Rolls</a></li>
  </ul></li>
  <li><a href="#histograms" id="toc-histograms" class="nav-link" data-scroll-target="#histograms">📊 Histograms</a></li>
  <li><a href="#two-dice" id="toc-two-dice" class="nav-link" data-scroll-target="#two-dice">🎲🎲 Two Dice</a></li>
  <li><a href="#symmetric-data" id="toc-symmetric-data" class="nav-link" data-scroll-target="#symmetric-data">☯️ Symmetric Data</a></li>
  <li><a href="#repeating-simulation" id="toc-repeating-simulation" class="nav-link" data-scroll-target="#repeating-simulation">🔁 Repeating Simulation</a>
  <ul class="collapse">
  <li><a href="#normal-data-with-replicate" id="toc-normal-data-with-replicate" class="nav-link" data-scroll-target="#normal-data-with-replicate">Normal Data with <code>replicate()</code></a></li>
  </ul></li>
  <li><a href="#fair-dice-check" id="toc-fair-dice-check" class="nav-link" data-scroll-target="#fair-dice-check">⚖️ Fair-Dice Check</a>
  <ul class="collapse">
  <li><a href="#biased-die" id="toc-biased-die" class="nav-link" data-scroll-target="#biased-die">Biased Die</a></li>
  <li><a href="#fair-vs-unfair-dice" id="toc-fair-vs-unfair-dice" class="nav-link" data-scroll-target="#fair-vs-unfair-dice">Fair vs.&nbsp;Unfair Dice</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#chapter-terms" id="toc-chapter-terms" class="nav-link" data-scroll-target="#chapter-terms">Chapter Terms</a></li>
  <li><a href="#practice-space" id="toc-practice-space" class="nav-link" data-scroll-target="#practice-space">📝 Practice Space</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#task-0" id="toc-task-0" class="nav-link" data-scroll-target="#task-0">Task 0</a></li>
  <li><a href="#task-1" id="toc-task-1" class="nav-link" data-scroll-target="#task-1">Task 1</a></li>
  <li><a href="#task-2" id="toc-task-2" class="nav-link" data-scroll-target="#task-2">Task 2</a></li>
  <li><a href="#task-3" id="toc-task-3" class="nav-link" data-scroll-target="#task-3">Task 3</a></li>
  <li><a href="#task-4" id="toc-task-4" class="nav-link" data-scroll-target="#task-4">Task 4</a></li>
  <li><a href="#save-and-upload" id="toc-save-and-upload" class="nav-link" data-scroll-target="#save-and-upload">Save and Upload</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/07-thoroughness/thoroughness.html">Thoroughness</a></li><li class="breadcrumb-item"><a href="../../chapters/07-thoroughness/ch15-probability-functions.html"><span class="chapter-title">Chapter 15: Probability functions</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Chapter 15: Probability functions</span></h1>
<p class="subtitle lead">Simulating Outcomes with R</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Probability is easier to understand when you can build and inspect examples yourself. In this chapter, you will use R to simulate random outcomes, visualize those results, and decide whether the patterns you see are reasonable. You will work with coin flips, dice rolls, bell-shaped data, and repeated simulations so that probability feels concrete rather than abstract. These are the same kinds of tools analysts use when they need to study uncertainty, test assumptions, or estimate risk.</p>
<p>By the end of Chapter 15 you will be able to:</p>
<ol type="1">
<li><p>⚡ Remember – Name <code>sample()</code>, <code>rnorm()</code>, and <code>replicate()</code>.</p></li>
<li><p>🔍 Understand – Explain how replacement and probability weights affect simulation results.</p></li>
<li><p>🛠 Apply – Simulate coins, dice, and normally distributed data with R code</p></li>
<li><p>✅ Check – Use tables, proportions, and histograms to verify whether simulated results make sense.</p></li>
<li><p>🧠 Interpret – Describe sampling variability and distinguish between fair and biased outcomes using simulated evidence.</p></li>
</ol>
<p>Keep these goals in mind as you move through each section.</p>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setting Up Your Notes</h2>
<p>To begin Chapter 15’s guided activity, follow these steps:</p>
<ol type="1">
<li>Open your course project for RStudio</li>
</ol>
<p>For those of you who <strong>have GitHub</strong> and a course project, navigate to your course folder and open your course project. This will open RStudio. Click “Pull” in the Git pane to get the latest version of the course materials. After completing work, save, stage, commit, and push.</p>
<p>If you <strong>don’t have GitHub</strong> or a course project, just open RStudio and set your working directory to your course folder.</p>
<ol start="2" type="1">
<li>Create a new file</li>
</ol>
<p>Create a new Quarto document for Chapter 15 and save it with a chapter-specific file name like <code>chapter15_notes.qmd</code></p>
<ol start="3" type="1">
<li>Follow along</li>
</ol>
<ul>
<li><p>Type in the goal, code, and comments provided in this document. Use memos to explain your thinking. Typing out journal-like reflections will help you internalize the concepts and make the learning more active.</p></li>
<li><p>Keep your work organized with headings. Since this chapter uses random simulation, run your document from top to bottom when you want reproducible results.</p></li>
</ul>
<section id="packages" class="level3">
<h3 class="anchored" data-anchor-id="packages">📦 Packages</h3>
<p>No extra packages are needed today. We’ll be using built-in stats functions.</p>
</section>
</section>
<section id="distribution" class="level2">
<h2 class="anchored" data-anchor-id="distribution">Distribution of Sums</h2>
<p>🎯 Identify the “Shape of Data” (or “Distribution of data”) is <em>optional reading</em>, but may help you answer questions in this chapter.</p>
<p>Below are examples of different histogram shapes that you may encounter in real data. <strong>Histograms</strong> are the count of values in each bin (or bar) of a histogram. The shape of the histogram can provide insights into the underlying <strong>distribution</strong> of the data, such as whether it is uniform, symmetric, skewed, or bimodal.</p>
<ol type="1">
<li><strong>Uniform</strong>: All bars have approximately the same height, indicating that all values are equally likely.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>Normal</strong>: This bell-shaped (symmetric) distribution is the left and right sides of the histogram are nearly mirror images of each other. Mean and median are approximately equal. <span class="math inline">\(Median \approx Mean\)</span>.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>Skewed Right</strong>: The right <em>tail</em> is longer than the left tail, indicating that there are a few high values that pull the mean to the right. <em>Positive skewness</em>. The mean is more right than the median due to extreme values. <span class="math inline">\(Median &lt; Mean\)</span>.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Histogram of a right-skewed distribution. Most values are clustered near the lower end, with a long tail extending to the right. A dashed blue line marks the median at about 6.6, and a solid red line marks the mean at about 9.6. The mean is to the right of the median, showing that a few high values pull the mean upward."></a></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<ol start="4" type="1">
<li><strong>Skewed Left</strong>: The left <em>tail</em> is longer than the right tail, indicating that there are a few low values that pull the mean to the left. <em>Negative skewness</em>. <span class="math inline">\(Median &gt; Mean\)</span>.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="1">
<li>Bimodal (Split Distribution): The distribution has two distinct peaks or modes. This suggests that the data might come from two different groups or processes. The mean and median may fall between the peaks, providing misleading summary statistics. Bimodal distributions often indicate hidden subpopulations.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-5-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</section>
<section id="warmup" class="level2">
<h2 class="anchored" data-anchor-id="warmup">Warm‑Up</h2>
<p>A data analyst uses <code>set.seed()</code> to ensure that random processes like sampling or simulation produce the same results each time the code is run (from top to bottom). This <strong>reproducibility</strong> is crucial for debugging, collaboration, and verifying results, as it guarantees consistency across analyses and users.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)  <span class="co"># 🎯 for reproducibility</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><em>If you re-run code more than once within your document, your values will not be the same. It is only the same when you run the code from top to bottom in one session.</em></p>
</section>
<section id="simulating" class="level2">
<h2 class="anchored" data-anchor-id="simulating">Simulating</h2>
<p><strong>Probability</strong> is the study of random outcomes. To understand probability, we need to be able to <strong>simulate</strong> random outcomes and inspect those results. R provides powerful tools for simulating random data, which allows us to explore concepts like <strong>sampling variability</strong>, distributions, and the effects of bias.</p>
<section id="coin-flips" class="level3">
<h3 class="anchored" data-anchor-id="coin-flips">🪙 Coin Flips</h3>
<p>In this first example, we’ll simulate flipping a coin 1,000 times and counting how many times it lands on tails. This simple experiment helps us understand the concept of a sample space, the role of randomness, and how to verify our results.</p>
<p>🎯 Flip 💰 1,000 fair coins (0 = heads, 1 = tails) and count tails.</p>
<p><strong>Sample Space</strong> “<span class="math inline">\(S\)</span>” is a collection (or set) of all possible outcomes in a random experiment.</p>
<p>Set Notation: <span class="math inline">\(S\)</span> = {Head, Tail}</p>
<ol type="1">
<li>🎯 Create the data through a simulation</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># sample(x, size, replace = FALSE, prob = NULL)</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>coins <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣<code>x = 0:1</code> means that we are sampling from either 0 or 1. As the researcher, I decide that 0 = heads and 1 = tails. We set <code>size = 1000</code> to flip the coin 1,000 times. We set <code>replace = TRUE</code> because we “put the coin back” each flip.</p>
<p><strong>replacement</strong> means that after we sample a value, we <em>“put it back”</em> into the pool of possible values for the next draw. This allows for the same value to be drawn multiple times, which is essential for simulating <strong>independent events</strong> like coin flips.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(coins)   <span class="co"># values in our data set</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(coins) <span class="co"># total number of flips</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(coins)  <span class="co"># type of object</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Coins contains 0 and 1 values where 1 represents tails of a coin flip. There are 1000 values in the integer vector.</p>
<p>💬 Prediction: How many tails are in our data set?</p>
<p>🎯 Use sum to count the number of tails because 1 = tails</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(coins)    </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Comment (your turn): How many tails are in our data set? Why does <code>sum(coins)</code> count the tails?</p>
<p>🚀 Explore and Play: Can you make a new data set where heads = 1? Try <code>1 - coins</code> and sum. Why would this work?</p>
<p>🛠 Break Things! What happens if <code>replace = FALSE</code> keeping <code>size = 1000</code>? Memo: paste the error message and 1 sentence on why it occurs.</p>
</section>
<section id="dice-rolls" class="level3">
<h3 class="anchored" data-anchor-id="dice-rolls">🎲 Dice Rolls</h3>
<p>🎯 Simulate 10,000 rolls of a fair 6‑sided die and plot the results.</p>
<p>Set Notation: <span class="math inline">\(S\)</span> = {1, 2, 3, 4, 5, 6}</p>
<p>💬 Prediction: How many times do you expect each face to appear? Will the values be exactly equal? Have a normal distribution? Something else? Type your answer before working ahead. <em>Keep whatever you typed, even if you are wrong. That’s the integrity of science!</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dice <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">10000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To investigate our hypothesis, we’ll visualize the results with a histogram using base R.</p>
</section>
</section>
<section id="histograms" class="level2">
<h2 class="anchored" data-anchor-id="histograms">📊 Histograms</h2>
<p>🎯 Use <code>hist()</code> to create a histogram of the dice rolls, showing the frequency of each face value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>?hist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>📜 The SYNTAX: <code>hist(x, breaks, col, main, xlab, ylab)</code></p>
<ul>
<li><p><code>x</code> is the data to plot</p></li>
<li><p><code>breaks</code> controls the number of bins (or bars)</p></li>
<li><p><code>col</code> sets the color of the bars</p></li>
<li><p><code>main</code> is the title of the plot</p></li>
<li><p><code>xlab</code> and <code>ylab</code> label the x- and y-axes</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dice,                  <span class="co"># The data to plot</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">6</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"lightblue"</span>,  <span class="co"># Color of the bars</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"10,000 Fair Die Rolls"</span>, <span class="co"># Title of the plot</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Face Value"</span>) <span class="co"># Label for the x-axis</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>🗣 The y-axis label is automatically set to “Frequency” by default.</p>
<p>🧐 NOTICE: Bars should be roughly equal height, forming a uniform distribution. That isn’t what we see.</p>
<p>When we specify breaks = 6, base R doesn’t create bins that align perfectly with our integer values 1-6. The bins slice the integers unevenly, leading to misleading bar heights.</p>
<p>🎯 Fix the breaks to align with die face values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dice,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">6.5</span>, <span class="at">by =</span> <span class="dv">1</span>),  <span class="co"># centers bars on 1:6</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"10,000 Fair Die Rolls (integer-aligned)"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Face Value"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>🗣 The bars look more even now.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative display for discrete data </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(dice), </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Counts by Die Face (table method)"</span>, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col    =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Face Value"</span>, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>🗣 The table() function provides an alternative way to display the data accurately.</p>
</section>
<section id="two-dice" class="level2">
<h2 class="anchored" data-anchor-id="two-dice">🎲🎲 Two Dice</h2>
<p>💬 Prediction: What histogram shape do you expect when summing the face value of two dice? Will the values be exactly equal? Have a normal distribution? Something else? Type your answer before working ahead. <em>Keep whatever you typed, even if you are wrong.</em></p>
<p>🎯 Roll two dice 10,000 times, add the results, plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>sum_two <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">10000</span>, <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">10000</span>, <span class="cn">TRUE</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Investigate</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sum_two,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">1.5</span>, <span class="fl">12.5</span>, <span class="at">by =</span> <span class="dv">1</span>),  <span class="co"># Creates bins centered on integers 2-12</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"salmon"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"Sum of Two Dice (10,000 trials)"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Total"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 The histogram shows a bell-shaped (normal) distribution, peaking around 7. This shape arises because there are more combinations to achieve sums near the middle (like 6, 7, and 8) compared to extreme sums (like 2 or 12).</p>
<hr>
<p>🚀 Explore and Play: We used the column “salmon” to create the figure. Test out other <code>col</code> options. Which are your favorite?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colors</span>()  <span class="co"># Lists all color names in R</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="symmetric-data" class="level2">
<h2 class="anchored" data-anchor-id="symmetric-data">☯️ Symmetric Data</h2>
<p>The functions <code>rnorm()</code> generates a vector of random numbers that form a normal (bell-shaped) distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>?rnorm  <span class="co"># Check the help file for rnorm()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>📜 The SYNTAX: <code>rnorm(n, mean = 0, sd = 1)</code></p>
<ul>
<li><p><code>n</code> is the number of random numbers to generate.</p></li>
<li><p><code>mean</code> is the average value of the distribution.</p></li>
<li><p><code>sd</code> is the standard deviation, controlling the spread of the distribution.</p></li>
</ul>
<p>🎯 Simulate 1,000 adult female heights ~ <span class="math inline">\(N(64, 2.5^2)\)</span> and inspect.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>heights <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">64</span>, <span class="at">sd =</span> <span class="fl">2.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(heights,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"yellowgreen"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"Simulated Female Heights"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Height (inches)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-19-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>The <code>breaks =</code> are unnecessary here because <code>hist()</code> automatically chooses appropriate bins for continuous data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="st">"Mean = "</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mean = "</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(heights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 64.11653</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="st">"SD = "</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "SD = "</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(heights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.508912</code></pre>
</div>
</div>
<p>🗣 The histogram shows a bell-shaped distribution of heights, centered around the mean of 64 inches. The spread of the data is consistent with the specified standard deviation of 2.5 inches.</p>
<p>Sample vs.&nbsp;Population Parameters: You might wonder, “Why aren’t the sample mean and standard deviation exactly 64 and 2.5?” This is because these are random samples from a normal distribution with those parameters. Each time we run the simulation, we get slightly different values due to <strong>sampling variability</strong>.</p>
<p>In summary, the function <code>rnorm()</code> generates random numbers from a normal distribution and is used for modeling normally distributed data using the parameters: number of values, mean, and standard deviation. This will only generate symmetric data.</p>
</section>
<section id="repeating-simulation" class="level2">
<h2 class="anchored" data-anchor-id="repeating-simulation">🔁 Repeating Simulation</h2>
<p>The function <code>replicate()</code> repeats an expression multiple times and collects the results. This control structure is like a loop is used to repeat sample estimate probabilities (simulations), resample data to estimate variability or confidence intervals (bootstrapping), model repeated trials of an experiment, generate synthetic data and more. This function is flexible as it can wrap any code, not just random generation.</p>
<p>That said, <strong>Monte Carlo simulations</strong> are the classic use case for <code>replicate()</code>. These simulations model are used to understand and manage risk and uncertainty using probabilities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>?replicate  <span class="co"># Check the help file for replicate()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>📜 The SYNTAX: <code>replicate(n, expr, simplify = "array")</code></p>
<ul>
<li><p><code>n</code> is the number of replications.</p></li>
<li><p><code>expr</code> is the expression (a language object, usually a call) to evaluate repeatedly.</p></li>
<li><p><code>simplify</code> indicates whether the result should be simplified to a vector, matrix or array if possible. The default is <code>"array"</code>.</p></li>
</ul>
<p>🎯 How variable is the number of tails in 5,000 flips? Repeat 100 times.</p>
<p>💰💰💰 …. 💰 That’s a lot of coins tosses!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>tails_100 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">expr =</span> <span class="fu">sum</span>(<span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="dv">5000</span>, <span class="cn">TRUE</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>replicate()</code> function:</p>
<ol type="1">
<li><p>Evaluates the entire expression 100 times (because <code>n = 100</code>)</p></li>
<li><p>Each evaluation is independent (gets its own random sampling)</p></li>
<li><p>Store the 100 results in a vector called <code>tails_100</code></p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tails_100)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2412    2477    2499    2502    2525    2582 </code></pre>
</div>
</div>
<p>🗣 Sampling variability show that the number of tails varies across these simulations, with a minimum of 2,412 tails and a maximum of 2,582 tails. The mean number of tails is approximately 2,499, which is close to the expected value of 2,500 for a fair coin.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tails_100,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"gold"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"Distribution of Tails in 5,000 Coin Flips (100 reps)"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Count of Tails"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-24-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>🗣 The spread shows sampling variability around the theoretical 2,500.</p>
<section id="normal-data-with-replicate" class="level3">
<h3 class="anchored" data-anchor-id="normal-data-with-replicate">Normal Data with <code>replicate()</code></h3>
<p>💭 Scenario. Pretend that the university is considering making specifications grading standard practice. The provost’s office says that if thirty percent or more of students oppose this, it would trigger a halt to the proposal. We want to know the risk of the proposal being halted.</p>
<p>We run a survey where student attitudes are measured on a continuous scale:</p>
<ul>
<li><p>0 = neutral,</p></li>
<li><p>negative values = oppose,</p></li>
<li><p>positive values = support.</p></li>
</ul>
<p>We’ll first run a random-sample survey of 50 students. Then we simulate many 50-student samples to see how much the number of opponents could vary. That variability informs the proposal planning.</p>
<section id="opinion-study" class="level4">
<h4 class="anchored" data-anchor-id="opinion-study">Opinion Study</h4>
<p>🎯 Generate 50 random numbers, compare each to zero, and count how many are below zero.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate 50 random numbers to represent student attitudes from survey</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># with a normal distribution (mean = 2, sd = 3)</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 While the average opinion is supportive (mean = 2), some individuals express opposition (negative values). In other words, some values are below zero because the mean is 2, but the standard deviation is 3, allowing for negative values. That’s normal sample-to-sample variation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mark who opposes (score &lt; 0), then count</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>below_zero <span class="ot">&lt;-</span> x <span class="sc">&lt;</span> <span class="dv">0</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(below_zero)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Count how many are below zero</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>count <span class="ot">&lt;-</span> <span class="fu">sum</span>(below_zero)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(count)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 We generated 50 random numbers from a normal distribution with mean 2 and standard deviation 3. We then compared each number to zero, yielding a logical vector indicating which are below zero. Finally, we summed the logical vector to count the number of values below zero.</p>
</section>
<section id="many-samples-simulation" class="level4">
<h4 class="anchored" data-anchor-id="many-samples-simulation">Many Samples Simulation</h4>
<p>Now simulate many realistic samples to understand how the count of opponents might bounce around.</p>
<p>Repeat this process multiple times using <code>replicate()</code>. This time, let’s generate 50 random numbers in 200 iterations.</p>
<p>🎯 Use <code>replicate</code> to repeat the counts across many simulated samples.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>values_below_zero <span class="ot">&lt;-</span> <span class="fu">replicate</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">200</span>,                                     <span class="co"># 200 hypothetical survey runs</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">expr =</span> <span class="fu">sum</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">3</span>) <span class="sc">&lt;</span> <span class="dv">0</span>)) <span class="co"># each run: 50 students, count opponents</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Order of Operations:</p>
<ol type="1">
<li><p><code>rnorm(n = 50, mean = 2, sd = 3)</code> generates a sample of 50 random numbers.</p></li>
<li><p><code>sum(... &lt; 0)</code> counts how many of those numbers are below zero.</p></li>
<li><p><code>replicate(n = 200, expr = ...)</code> repeats this process 200 times.</p></li>
<li><p>The result is a vector of counts, one for each of the 200 samples.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Investigate</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Useful summaries for discussion</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(values_below_zero)   <span class="co"># typical number of opponents</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.77</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(values_below_zero)     <span class="co"># how much the count varies</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.121831</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(values_below_zero, <span class="fu">c</span>(.<span class="dv">1</span>,.<span class="dv">5</span>,.<span class="dv">9</span>))  <span class="co"># 10th/50th/90th percentiles</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>10% 50% 90% 
  9  13  17 </code></pre>
</div>
</div>
<p>🗣 The mean indicates that, on average, the typical count of those opposed is about 13 across many samples of 50 students. The standard deviation shows that the count of opponents can vary by about 3.1 from sample to sample. The percentiles provide additional insights into the distribution of opponent counts, indicating that in 10% of the samples, there are 9 or fewer opponents, while in 90% of the samples, there are 17 or fewer opponents.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example planning thresholds (adjust to your context)</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(values_below_zero <span class="sc">&gt;=</span> <span class="dv">15</span>)  <span class="co"># How often do we see ≥15 opponents out of 50?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.28</code></pre>
</div>
</div>
<p>If at least 15 opponents trigger a halt, the proposal’s risk of being halted is about 28% based on our simulations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative way to calculate probability of halt</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># One-line simulation estimate:</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>risk_halt <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">replicate</span>(<span class="dv">200</span>, <span class="fu">sum</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="dv">2</span>, <span class="dv">3</span>) <span class="sc">&lt;</span> <span class="dv">0</span>)) <span class="sc">&gt;=</span> <span class="dv">15</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>risk_halt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Integer-aligned histogram + shading + on-plot probability</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>max_count <span class="ot">&lt;-</span> <span class="fu">max</span>(values_below_zero)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>breaks_int <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">2.5</span>, max_count <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Investigate</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(values_below_zero,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> breaks_int,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"lightpink"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"Distribution of Opponents in 50-Student Surveys (200 reps)"</span>,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Count of Values Below Zero"</span>)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> threshold, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="co"># Halt threshold</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(values_below_zero), <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)  <span class="co"># Mean line</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, </span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Halt Threshold (15)"</span>, <span class="st">"Mean Count"</span>),</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>),</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>),</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">bg =</span> <span class="st">"white"</span>,</span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"o"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-31-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>🗣 Each bar shows how often a particular count of opponents appeared across the 200 samples. The center of the histogram is the typical count. The spread shows how much that count changes from sample to sample, even if the underlying social climate doesn’t change. About 1 in 4 samples hit the halt threshold (≥15).</p>
</section>
</section>
</section>
<section id="fair-dice-check" class="level2">
<h2 class="anchored" data-anchor-id="fair-dice-check">⚖️ Fair-Dice Check</h2>
<p><strong>Probability weights</strong> in <code>sample()</code> let you simulate biased outcomes. Recall the syntax:</p>
<p>📜 The SYNTAX: <code>sample(x, size, replace = FALSE, prob = NULL)</code></p>
<p>A <strong>fair outcome</strong> means that each outcome in the sample space has an equal chance of occurring. For example, a fair six-sided die has an equal probability of landing on any of its faces (1 through 6), which is 1/6 or approximately 0.1667 for each face.</p>
<section id="biased-die" class="level3">
<h3 class="anchored" data-anchor-id="biased-die">Biased Die</h3>
<p>A <strong>biased outcome</strong> means that some outcomes are more likely to occur than others. For example, a biased six-sided die might have a higher probability of landing on certain faces, such as 1 and 6, while other faces (like 2, 3, 4, and 5) have lower probabilities.</p>
<p>The <code>prob</code> parameter specifies the probability weights for each element in the sampling pool.</p>
<p>🎯 Simulate rolling a biased die 1,000 times with specified probabilities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>rolls <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1000</span>, <span class="at">prob =</span> <span class="fu">c</span>(.<span class="dv">12</span>,.<span class="dv">13</span>,.<span class="dv">07</span>,.<span class="dv">23</span>,.<span class="dv">22</span>,.<span class="dv">23</span>), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 This simulates rolling one biased or “loaded” die <code>1000</code> times. The length of the prob vector must match the number of sampled values (x = <code>1:6</code>). The weights usually sum to 1; R will normalize them if they don’t.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Verify that relative frequencies should be near the weights</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(rolls)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>rolls
    1     2     3     4     5     6 
0.130 0.133 0.076 0.222 0.223 0.216 </code></pre>
</div>
</div>
<p>🗣 The relative frequencies should roughly match the specified probabilities, confirming the bias in the die. The results may vary slightly due to randomness, but over many rolls, they should converge to the specified probabilities.</p>
<hr>
<p>🛠 Break Things! What happens if the length of <code>prob</code> does not match the length of <code>x</code>? Paste the error message and 1 sentence on why it occurs. What happens if the <code>prob</code> values do not sum to 1? Can you have negative probabilities? You could try <code>sample(1:6, 10, replace = TRUE, prob = c(.5, .5))</code> and try <code>sample(1:6, 10, replace = TRUE, prob = c(.1, .2, 0.2, .05, .2, .05, .4))</code> and <code>sample(1:6, 1000, prob = c(.22,-.13,.07,.23,.22,.23), replace = TRUE)</code>. Explain what happens and what the rules are for the <code>prob</code> argument in <code>sample()</code>. ___</p>
</section>
<section id="fair-vs-unfair-dice" class="level3">
<h3 class="anchored" data-anchor-id="fair-vs-unfair-dice">Fair vs.&nbsp;Unfair Dice</h3>
<p>💭 Scenario. You are playing a dice game with a “friend” who claims their dice are fair. 🤔 Your “friend’s” dice look suspiciously unfair. Compare it to our fair dice. We’ll test the your friend’s dice against your fair dice.</p>
<p>🎯 Simulate rolling two biased dice 1,000 times and compare to two fair dice. We’ll compare your friend’s results to fair dice by adding the the face values of the dice then</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">8000</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>biased <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">12</span>, .<span class="dv">13</span>, .<span class="dv">07</span>, .<span class="dv">23</span>, .<span class="dv">22</span>, .<span class="dv">23</span>)  <span class="co"># sums to 1</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>friend_sum <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> biased) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> biased)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ Test</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>fair_sum <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1000</span>, <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1000</span>, <span class="cn">TRUE</span>) <span class="co"># no 'prob' = equal chance</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 The simulates rolling two biased dice 1000 times. This is like you and a friend each rolling two dice 1000 times simultaneously.</p>
<p>🎯 Compare the distributions of the sum of two fair dice face values from your friend’s biased dice.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportions of each sum</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>ploaded <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(friend_sum))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>pfair <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(fair_sum))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Investigate</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Side-by-side bar plot</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>face_props <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">Bias =</span> ploaded, <span class="at">Fair =</span> pfair)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(face_props,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">beside =</span> <span class="cn">TRUE</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col    =</span> <span class="fu">c</span>(<span class="st">"tomato"</span>, <span class="st">"steelblue"</span>),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">main   =</span> <span class="st">"Probabilities (2 Dice, 1000 rolls)"</span>,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab   =</span> <span class="st">"Added Face Values"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab   =</span> <span class="st">"Proportion"</span>)</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Loaded"</span>, <span class="st">"Fair"</span>),</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"tomato"</span>, <span class="st">"steelblue"</span>), <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="ch15-probability-functions_files/figure-html/unnamed-chunk-37-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="ch15-probability-functions_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>🗣 Comment: What is the shape of the red bars compared with the blue?</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In this chapter, you used R to study probability through simulation. You learned how <code>set.seed()</code> supports reproducibility, how <code>sample()</code> can simulate discrete outcomes such as coin flips and dice rolls, and how <code>hist()</code> helps you visualize the shape of simulated results. You also used <code>rnorm()</code> to generate bell-shaped data and <code>replicate()</code> to repeat simulations so you could examine variability across many runs. Finally, you used probability weights in <code>sample()</code> to compare fair and biased outcomes and to judge whether simulated results matched what you would expect from a fair process.</p>
</section>
<section id="chapter-terms" class="level2">
<h2 class="anchored" data-anchor-id="chapter-terms">Chapter Terms</h2>
<p><strong>Biased Outcome</strong>: An outcome in a random process where some results are more likely than others, so the outcomes are not equally likely.</p>
<p><strong>Distribution</strong>: The pattern of possible values of a variable, together with how likely those values are or how often they occur.</p>
<p><strong>Fair Outcome</strong>: An outcome in a random process where all possible results are equally likely. For example, in a fair six-sided die, each face has probability 1/6.</p>
<p><strong>Histogram</strong>: A graph for numerical data that groups values into intervals (bins) and shows how many observations fall in each bin.</p>
<p><strong>Independent Events</strong>: Events where the occurrence of one does not change the probability of the other. In probability notation, events A and B are independent when <span class="math inline">\(P(A \cap B) = P(A)P(B)\)</span>; equivalently, knowing that one happened does not change the probability of the other.</p>
<p><strong>Monte Carlo Simulation</strong>: A simulation method that uses repeated random sampling to approximate probabilities, study uncertainty, or estimate numerical results.</p>
<p><strong>Normal Distribution</strong>: A continuous, bell-shaped distribution that is symmetric around its center, with most values near the mean and fewer values farther away.</p>
<p><strong>Probability</strong>: A number from 0 to 1 that describes how likely an event is to occur, where 0 means impossible and 1 means certain.</p>
<p><strong>Probability Weights</strong>: Numbers that control how likely each value is to be selected in a random sample. In R, the prob argument in <code>sample()</code> supplies these weights; they must be nonnegative and do not have to add up to 1.</p>
<p><strong>Replacement</strong>: A sampling method where a selected value is put back before the next draw, so it can be chosen again. In R, this is controlled by replace = TRUE in functions like <code>sample()</code>.</p>
<p><strong>Reproducibility</strong>: The ability to get the same computational results again by using the same data, code, steps, and analysis conditions.</p>
<p><strong>Sample Space</strong>: The set of all possible outcomes of a random experiment.</p>
<p><strong>Sampling Variability</strong>: The natural sample-to-sample differences that occur because different random samples from the same population usually produce different statistics.</p>
<p><strong><code>set.seed()</code></strong>: An R function that sets the starting state of the random number generator so random operations can be repeated and produce the same results again.</p>
<p><strong>Simulation</strong>: A model of a random process that generates artificial outcomes so you can study what might happen and estimate probabilities or patterns.</p>
<p><strong>Uniform Distribution</strong>: A distribution in which all possible outcomes in the range are equally likely.</p>
</section>
<section id="practice-space" class="level2">
<h2 class="anchored" data-anchor-id="practice-space">📝 Practice Space</h2>
<p>In this Practice Space, you are expected to:</p>
<ul>
<li>simulate outcomes using functions such as <code>sample()</code> and <code>rnorm()</code></li>
<li>use <code>replicate()</code> when a task asks you to repeat a simulation many times</li>
<li>store requested objects with the exact names given in the task</li>
<li>check your results using tools such as <code>head()</code>, <code>table()</code>, <code>mean()</code>, <code>length()</code>, <code>any()</code>, or other appropriate checks</li>
<li>write short interpretations that explain what the simulation shows, not just what code you ran</li>
</ul>
<p>When a task asks a yes/no question or asks whether a result seems reasonable, answer in a short memo after your code and checks.</p>
<p>Replace every <code>____</code> placeholder and any TODO comment with working code or a short written response. Run each section and make sure the requested objects appear in the Environment. For every task, use the pattern 🎯 Goal → ⚡ Code → ✅ Checks → 🗣 Explain.</p>
<p>You will submit your <code>chapter15_practice.qmd</code>, your rendered <code>chapter15_practice.html</code>(optional), and your <code>chapter15_practice.RData</code> workspace file.</p>
<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<ol type="1">
<li>Create a <strong>new Quarto file</strong> in your course folder and save it as <code>chapter15_practice.qmd</code>.</li>
</ol>
<ul>
<li>Test Render your document often so you can catch formatting problems and code errors early.</li>
<li>You may submit the rendered file <code>chapter15_practice.html</code> if you successfully create it, but the HTML file is optional.</li>
</ul>
<ol start="2" type="1">
<li>Use the heading structure taught earlier in the chapter.</li>
</ol>
<p>Your Quarto setup for Chapter 15 should include headings, section numbering, and a table of contents, and you should render often to check both formatting and errors.</p>
<ol start="3" type="1">
<li>📦 No extra packages are required</li>
</ol>
<p>This chapter uses base R functions for probability and simulation, so your code should run cleanly in a fresh R session without loading extra packages.</p>
<ol start="4" type="1">
<li>Make your simulation work reproducible.</li>
</ol>
<ul>
<li>Because this chapter uses random simulation, use <code>set.seed()</code> when you want your simulated results to be reproducible.</li>
<li>Run your document from top to bottom to confirm that your output, objects, and explanations all match.</li>
</ul>
<ol start="5" type="1">
<li>Memo your work with the 🎯 / ⚡ / ✅ / 🗣</li>
</ol>
<ul>
<li>🎯 a memo before the code chunk that states the goal of the code and what you are trying to learn, check, or demonstrate</li>
<li>⚡ the code chunk itself</li>
<li>✅ any needed checks after the code</li>
<li>🗣 a memo after the code chunk that explains what you learned, discovered, or confirmed</li>
<li>🗣 answers to all comment questions included in the task</li>
</ul>
<p>👀 If you <strong>used help</strong> while working, document it in a memo. For example, if you used an LLM or another outside resource to understand an error or concept, briefly disclose that use and explain what help you received. <strong>Type all code yourself.</strong> This is part of the course expectation for AI-supported learning and memo-based workflow.</p>
<hr>
<p>Follow this template for each coding task.</p>
<p>🎯 What is the goal of the code? What am I trying to learn, check, or demonstrate?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#⚡Code </span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>your_code <span class="ot">&lt;-</span> <span class="st">"here"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Include checks that fit your object</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(your_code)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(your_code)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(your_code)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(your_code)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(your_code)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(your_code)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣/🪞 What I learned / Next step. 1–2 sentences.</p>
<hr>
</section>
<section id="task-0" class="level3">
<h3 class="anchored" data-anchor-id="task-0">Task 0</h3>
<p><strong>Make your simulation work reproducible.</strong></p>
<p>🎯 Set a seed for reproducibility. We’ll use the same seed so everyone gets the same simulated results.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  Set seed for reproducibility</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Explain how <code>set.seed()</code> supports reproducibility in your own words. Why does it need to be near the top of your document before any simulation code?</p>
</section>
<section id="task-1" class="level3">
<h3 class="anchored" data-anchor-id="task-1">Task 1</h3>
<p>💭 Scenario. 🧙‍♂️🗡️📜 Your friend shows up to your DnD game with a big 3D printed 20-sided die and claims it is fair. You decide to test it. For practice, you will simulate what 300 rolls of a fair 20-sided die can look like, then check whether the results look roughly fair overall. <a href="https://www.youtube.com/watch?v=-gp7AbYD9NI">How to Make Fair DnD Dice from ANY Shape</a></p>
<p>🎯 Simulate 300 rolls of a fair 20-sided die using the values <code>1:20</code> and store the result in <strong><code>big_die</code></strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ </span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>big_die <span class="ot">&lt;-</span> <span class="fu">sample</span>(___, <span class="at">size =</span> ___, <span class="at">replace =</span> ___)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>big_die_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(big_die)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Did you roll a 20?</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(big_die_counts), <span class="dv">3</span>)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(big_die_counts)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(big_die <span class="sc">==</span> ___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Comment: Does this simulated die look roughly fair? Explain using the overall pattern of counts, not just whether a 20 appeared. A fair die should have counts that are similar but not exactly equal.</p>
</section>
<section id="task-2" class="level3">
<h3 class="anchored" data-anchor-id="task-2">Task 2</h3>
<p>💭 Scenario. A game store is running a weekend probability demo and asks you to help analyze whether a 20-sided die behaves the way a fair die should over many rolls. Your job is to simulate many D20 rolls, check the results, and decide whether the pattern looks reasonable for a fair die.</p>
<section id="step-1" class="level4">
<h4 class="anchored" data-anchor-id="step-1">Step 1</h4>
<p><strong>D20 marathon</strong></p>
<p>🎯 Simulate 5221 rolls of a fair 20-sided die. Store as <strong><code>boring_weekend</code></strong> using <code>sample()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ </span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>boring_weekend <span class="ot">&lt;-</span> <span class="fu">sample</span>(___, <span class="at">size =</span> ___, <span class="at">replace =</span> ___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>💬 Prediction: What do you expect the frequency table for a fair D20 to look like? Should each face appear about the same number of times, or should some values be much more common than others? Explain your prediction before running the check. <em>Keep whatever you typed, even if you are wrong. That’s the integrity of science!</em></p>
</section>
<section id="step-2" class="level4">
<h4 class="anchored" data-anchor-id="step-2">Step 2</h4>
<p>✅ <strong>Quick frequency check</strong></p>
<p>🎯 Create <strong><code>d20_counts</code></strong>: a table of how many times each face appeared.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ </span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>d20_counts <span class="ot">&lt;-</span> <span class="fu">__</span>(_______)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅ Quick check</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(d20_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Comment on how similar or different the counts are across the values in the table.</p>
</section>
<section id="step-3" class="level4">
<h4 class="anchored" data-anchor-id="step-3">Step 3</h4>
<p><strong>Hit rate</strong></p>
<p>🎯 Find the proportion of rolls that were natural 20s. Then compare that result to the fair-die benchmark of 0.05.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  </span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(boring_weekend <span class="sc">==</span> ___)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(<span class="fu">mean</span>(boring_weekend <span class="sc">==</span> ___) <span class="sc">-</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Comment: Based on both the full frequency table from Step 2 and the natural-20 rate here, does the die appear to be fair? Explain why.</p>
<p>💡 <strong>Tip:</strong> A fair die should have counts that are roughly even overall and a natural-20 rate close to 0.05, but not perfectly exact.</p>
</section>
</section>
<section id="task-3" class="level3">
<h3 class="anchored" data-anchor-id="task-3">Task 3</h3>
<p>💭 Scenario. A hospital is considering ordering new blankets for newborns. They want to know how many blankets they should order in each size. The hospital has data on newborn lengths, which are normally distributed with a mean of 20 inches and a standard deviation of 0.9 inches. The hospital wants to know how many babies are likely to be longer than 23 inches, which would require larger blankets.</p>
<section id="step-1" class="level4">
<h4 class="anchored" data-anchor-id="step-1">Step 1</h4>
<p><strong>Baby-blanket test</strong></p>
<p>🎯 Simulate 100 newborn lengths (inches) with mean 20.0, SD 0.9. Store as <strong><code>blanketed_babies</code></strong>. Use <code>rnorm()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚡ </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>blanketed_babies <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(___, <span class="at">mean =</span> ___, <span class="at">sd =</span> ___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Comment: What do you expect the distribution of baby lengths to look like? Will the values be exactly equal? Have a normal distribution? Something else? Type your answer before working ahead. <em>Keep whatever you typed, even if you are wrong. That’s the integrity of science!</em></p>
</section>
<section id="step-2" class="level4">
<h4 class="anchored" data-anchor-id="step-2">Step 2</h4>
<p><strong>Too long?</strong></p>
<p>🎯 Using <code>any()</code>, check whether any babies in <code>blanketed_babies</code> are longer than 23 inches. Then count how many are over 23 inches. Do not store the result as a new object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  </span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(________________)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(________________)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Comment: Yes or No — based on this simulation, does the hospital appear to need longer blankets?</p>
</section>
<section id="step-3" class="level4">
<h4 class="anchored" data-anchor-id="step-3">Step 3</h4>
<p>⚠️ <strong>Week-to-week risk</strong></p>
<p>🎯 Repeat Steps 1 and 2 for 1000 simulated weeks. Store a vector named <code>weeks_too_long</code> that records, for each simulated week, <strong>how many babies were longer than 23 inches</strong>. Hint: use <code>replicate()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>weeks_too_long <span class="ot">&lt;-</span> <span class="fu">replicate</span>(___, <span class="fu">sum</span>(<span class="fu">rnorm</span>(___, <span class="at">mean =</span> ___, <span class="at">sd =</span> ___) <span class="sc">&gt;</span> ___))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ✅  </span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(weeks_too_long)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(weeks_too_long)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(weeks_too_long <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(weeks_too_long)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>🗣 Comment: In these 1000 simulated weeks, how often do you see at least one baby longer than 23 inches? What does that suggest about whether the hospital should keep some larger blankets available?</p>
</section>
</section>
<section id="task-4" class="level3">
<h3 class="anchored" data-anchor-id="task-4">Task 4</h3>
<p>🤔 <strong>Reflect</strong></p>
<p>📝 Write a short paragraph reflecting on the utility of <code>replicate()</code> in the week-to-week risk simulation from Task 3, Step 3.</p>
<p>✍️ EXPLANATION: <code>"___"</code></p>
</section>
<section id="save-and-upload" class="level3">
<h3 class="anchored" data-anchor-id="save-and-upload">Save and Upload</h3>
<ol type="1">
<li>You will be submitting <strong>both</strong> the <code>chapter15_practice.qmd</code> Document <strong>and</strong> the workspace file (<code>.RData</code>). Submit the rendered <code>chapter15_practice.html</code> file if you successfully rendered it and want to share it, but it is optional.</li>
</ol>
<p>📖 <strong>Review</strong> The workspace file (<code>.RData</code>) is all the objects in your environment that you created in this chapter.</p>
<p>🎯 Save your work and submit to Canvas.</p>
<p><strong>Step 1: Sweep your Environment (start clean).</strong><br>
Click the 🧹 <strong>broom icon</strong> in the Environment pane to clear objects.</p>
<p><strong>Step 2: Run everything top-to-bottom.</strong><br>
Use <strong>Run → Run All</strong> to execute every chunk in order.</p>
<p><strong>Step 3: Save and submit.</strong></p>
<p>You can save the workspace (objects in your environment) by running the following command in a code chunk of the Quarto Document document:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save.image</span>(<span class="st">"chapter15_practice.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Or you can click the 💾 “Save workspace as” button in the Environment pane.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/lorrainegaudio\.github\.io\/guided-activities-for-learning-R-workflow\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/07-thoroughness/thoroughness.html" class="pagination-link" aria-label="Thoroughness">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Thoroughness</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/07-thoroughness/ch16-ggplot2.html" class="pagination-link" aria-label="Chapter 16: ggplot2">
        <span class="nav-page-text"><span class="chapter-title">Chapter 16: ggplot2</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Goal, Code, Verify, Reflect</p>
</div>   
    <div class="nav-footer-center">
<p>Boise State University</p>
</div>
    <div class="nav-footer-right">
<p><a href="mailto:lorrainegaudio@boisestate.edu">lorrainegaudio@boisestate.edu</a></p>
</div>
  </div>
</footer>
<script>
document.addEventListener("DOMContentLoaded", function () {
  if (typeof bootstrap === "undefined") return;

  function normalizeTerm(text) {
    return String(text || "")
      .toLowerCase()
      .replace(/[’']/g, "")
      .replace(/[^a-z0-9]+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function getDefinitionNodes(chapterTermsContainer) {
    const nodes = [];

    if (!chapterTermsContainer) return nodes;

    /*
      Quarto often places the id on a <section>, not directly on the heading.
      In that case, the term paragraphs are children inside the section.
    */
    if (chapterTermsContainer.tagName === "SECTION") {
      Array.from(chapterTermsContainer.children).forEach(function (child) {
        if (child.matches("p, li")) {
          nodes.push(child);
        }
      });

      return nodes;
    }

    /*
      Fallback: if the id is on the heading itself, collect paragraphs
      after the heading until the next major section.
    */
    let node = chapterTermsContainer.nextElementSibling;

    while (node && !["H1", "H2"].includes(node.tagName)) {
      if (node.matches && node.matches("p, li")) {
        nodes.push(node);
      }

      node = node.nextElementSibling;
    }

    return nodes;
  }

  function getChapterTerms() {
    const terms = new Map();
    const chapterTermsContainer = document.getElementById("chapter-terms");
    const definitionNodes = getDefinitionNodes(chapterTermsContainer);

    definitionNodes.forEach(function (node) {
      const strong = node.querySelector("strong");
      if (!strong) return;

      const fullText = node.textContent.replace(/\s+/g, " ").trim();
      const strongTerm = strong.textContent.replace(/\s+/g, " ").trim();
      const colonIndex = fullText.indexOf(":");

      if (colonIndex === -1) return;

      const fullTerm = fullText.slice(0, colonIndex).trim();
      const definition = fullText.slice(colonIndex + 1).trim();

      if (!strongTerm || !definition) return;

      const entry = {
        title: fullTerm,
        definition: definition
      };

      terms.set(normalizeTerm(strongTerm), entry);
      terms.set(normalizeTerm(fullTerm), entry);
    });

    return terms;
  }

  const chapterTerms = getChapterTerms();

  document.querySelectorAll(".glossary-term").forEach(function (termElement) {
    const dataTerm = termElement.getAttribute("data-term");
    const requestedTerm = dataTerm && dataTerm.trim()
      ? dataTerm.trim()
      : termElement.textContent.trim();

    const glossaryEntry = chapterTerms.get(normalizeTerm(requestedTerm));

    if (!glossaryEntry) {
      termElement.classList.add("glossary-term-missing");
      termElement.setAttribute("title", "Definition not found in Chapter Terms.");
      console.warn("Glossary definition not found for:", requestedTerm);
      return;
    }

    termElement.setAttribute("tabindex", "0");
    termElement.setAttribute("role", "button");
    termElement.setAttribute("data-bs-toggle", "popover");
    termElement.setAttribute("data-bs-trigger", "hover focus");
    termElement.setAttribute("data-bs-placement", "auto");
    termElement.setAttribute("data-bs-title", glossaryEntry.title);
    termElement.setAttribute("data-bs-content", glossaryEntry.definition);

    const existingPopover = bootstrap.Popover.getInstance(termElement);
    if (existingPopover) {
      existingPopover.dispose();
    }

    new bootstrap.Popover(termElement, {
      container: "body",
      html: false,
      customClass: "glossary-popover"
    });
  });
});
</script>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>